namespace Wonga.QA.Framework.Msmq.Enums.Risk
{
    public enum EmploymentPositionEnum
    {
        Actor = 1,
        Administration = 2,
        BusDriver = 3,
        BusinessDevelopment = 4,
        BusinessOwner = 5,
        Consultancy = 6,
        Doctor = 7,
        Engineering = 8,
        Marketing = 9,
        CabDriver = 10,
        Musician = 11,
        Nurse = 12,
        Other = 13,
        Sales = 14,
        SeniorManagerDirector = 15,
        Services = 16,
        Teacher = 17,
        TruckDriver = 18,
        Firefighter = 19,
        Management = 20,
        TaxiDriver = 21,
        EmergencyServices = 22,
        Government = 23,
        Healthcare = 24,
        Manufacturing = 25,
        MiningAgriculture = 26,
        Professional = 27,
        RestaurantFoodServices = 28,
        Retail = 29,
        Technical = 30,
        Trades = 31,
    }
}
