namespace Wonga.QA.Framework.Msmq.Enums.Risk
{
    public enum EmploymentIndustryEnum
    {
        Accountancy = 1,
        Advertising = 2,
        BusinessConsultancy = 3,
        CallCentreOperations = 4,
        Cleaning = 5,
        ComputerServices = 6,
        Construction = 7,
        Education = 8,
        Electricity = 9,
        Finance = 10,
        Health = 11,
        HotelsRestaurants = 12,
        Insurance = 13,
        LegalServices = 14,
        LeisureCulture = 15,
        Manufacturing = 16,
        Mining = 17,
        PublicAdministration = 18,
        Publishing = 19,
        Property = 20,
        ResearchDevelopment = 21,
        Retail = 22,
        TelecomsInternet = 23,
        Transportation = 24,
        Other = 25,
        Services = 27,
        PublicServices = 28,
        Forestry = 29,
        Agriculture = 30,
        Hunting = 31,
        EnergyIndustry = 32,
    }
}
