using System.ComponentModel;
namespace Wonga.QA.Framework.Api.Enums
{
    public enum BankNamesPlEnum
    {
        [Description("NarodowyBankPolski")]
        NarodowyBankPolski,
        [Description("PowszechnaKasaOszczędnościBankPolskiSA")]
        PowszechnaKasaOszczędnościBankPolskiSA,
        [Description("BankHandlowywWarszawieSA")]
        BankHandlowywWarszawieSA,
        [Description("INGBankŚląskiSA")]
        INGBankŚląskiSA,
        [Description("BankBPHSA")]
        BankBPHSA,
        [Description("BankZachodniWBKSA")]
        BankZachodniWBKSA,
        [Description("BankGospodarstwaKrajowego")]
        BankGospodarstwaKrajowego,
        [Description("BREBankSAmBank11402004MultiBank11402017")]
        BREBankSAmBank11402004MultiBank11402017,
        [Description("BREBankSA")]
        BREBankSA,
        [Description("BankMillenniumSA")]
        BankMillenniumSA,
        [Description("BankPolskaKasaOpiekiSA")]
        BankPolskaKasaOpiekiSA,
        [Description("HSBCBankPolskaSA")]
        HSBCBankPolskaSA,
        [Description("MeritumBankICBSA")]
        MeritumBankICBSA,
        [Description("BankPocztowySA")]
        BankPocztowySA,
        [Description("NORDEABANKPOLSKASA")]
        NORDEABANKPOLSKASA,
        [Description("GetinNobleBankSA")]
        GetinNobleBankSA,
        [Description("EuroBankSA")]
        EuroBankSA,
        [Description("KredytBankSA")]
        KredytBankSA,
        [Description("BankOchronyŚrodowiskaSA")]
        BankOchronyŚrodowiskaSA,
        [Description("MercedesBenzBankPolskaSA")]
        MercedesBenzBankPolskaSA,
        [Description("BNPPARIBASBANKPOLSKASA")]
        BNPPARIBASBANKPOLSKASA,
        [Description("SGBBankSA")]
        SGBBankSA,
        [Description("RBSBankPolskaSA")]
        RBSBankPolskaSA,
        [Description("INVESTBANKSA")]
        INVESTBANKSA,
        [Description("DZBANKPolskaSA")]
        DZBANKPolskaSA,
        [Description("RaiffeisenBankPolskaSA")]
        RaiffeisenBankPolskaSA,
        [Description("SocieteGeneraleSAOddziałwPolsce")]
        SocieteGeneraleSAOddziałwPolsce,
        [Description("PolskiBankPrzedsiębiorczościSA")]
        PolskiBankPrzedsiębiorczościSA,
        [Description("DeutscheBankPolskaSA")]
        DeutscheBankPolskaSA,
        [Description("PekaoBankHipotecznySA")]
        PekaoBankHipotecznySA,
        [Description("DeutscheBankPBCSA")]
        DeutscheBankPBCSA,
        [Description("BANKPOLSKIEJSPÓŁDZIELCZOŚCISA")]
        BANKPOLSKIEJSPÓŁDZIELCZOŚCISA,
        [Description("CreditAgricoleBankPolskaSA")]
        CreditAgricoleBankPolskaSA,
        [Description("IdeaBankSA")]
        IdeaBankSA,
        [Description("RabobankPolskaSA")]
        RabobankPolskaSA,
        [Description("BankGospodarkiŻywnościowejSA")]
        BankGospodarkiŻywnościowejSA,
        [Description("FCEBankPolskaSA")]
        FCEBankPolskaSA,
        [Description("SantanderConsumerBankSA")]
        SantanderConsumerBankSA,
        [Description("VOLKSWAGENBANKPOLSKASA")]
        VOLKSWAGENBANKPOLSKASA,
        [Description("FiatBankPolskaSA")]
        FiatBankPolskaSA,
        [Description("BREBankHipotecznySA")]
        BREBankHipotecznySA,
        [Description("ToyotaBankPolskaSA")]
        ToyotaBankPolskaSA,
        [Description("BankDnBNORDPolskaSA")]
        BankDnBNORDPolskaSA,
        [Description("BankofTokyoMitsubishiUFJPolskaSA")]
        BankofTokyoMitsubishiUFJPolskaSA,
        [Description("BanquePSAFinanceSAOddziałwPolsce")]
        BanquePSAFinanceSAOddziałwPolsce,
        [Description("SvenskaHandelsbankenABSAOddziałwPolsce")]
        SvenskaHandelsbankenABSAOddziałwPolsce,
        [Description("RCIBankPolskaSA")]
        RCIBankPolskaSA,
        [Description("SygmaBanqueSocieteAnonymeSAOddziałwPolsce")]
        SygmaBanqueSocieteAnonymeSAOddziałwPolsce,
        [Description("DexiaKommunalkreditBankPolskaSA")]
        DexiaKommunalkreditBankPolskaSA,
        [Description("NykreditRealkreditASSAOddziałwPolsce")]
        NykreditRealkreditASSAOddziałwPolsce,
        [Description("CreditAgricoleCorporateandInvestmentBankSAOddziałwPolsce")]
        CreditAgricoleCorporateandInvestmentBankSAOddziałwPolsce,
        [Description("PolbankEFGSA")]
        PolbankEFGSA,
        [Description("BNPPARIBASSAOddziałwPolsce")]
        BNPPARIBASSAOddziałwPolsce,
        [Description("DanskeBankASSAOddziałwPolsce")]
        DanskeBankASSAOddziałwPolsce,
        [Description("SkandinaviskaEnskildaBankenABSAOddziałwPolsce")]
        SkandinaviskaEnskildaBankenABSAOddziałwPolsce,
        [Description("BancoMaisSASAOddziałwPolsce")]
        BancoMaisSASAOddziałwPolsce,
        [Description("CAIXABANKSASPÓŁKAAKCYJNAODDZIAWPOLSCE")]
        CAIXABANKSASPÓŁKAAKCYJNAODDZIAWPOLSCE,
        [Description("ElavonFinancialServicesLimitedSpółkazograniczonąodpowiedzialnościąOddziałwPolsce")]
        ElavonFinancialServicesLimitedSpółkazograniczonąodpowiedzialnościąOddziałwPolsce,
        [Description("BNPParibasSecuritiesServicesSKAOddziałwPolsce")]
        BNPParibasSecuritiesServicesSKAOddziałwPolsce,
        [Description("BancoEspiritoSantodeInvestimentoSASpółkaAkcyjnaOddziałwPolsce")]
        BancoEspiritoSantodeInvestimentoSASpółkaAkcyjnaOddziałwPolsce,
        [Description("GetBankSA")]
        GetBankSA,
        [Description("AliorBankSA")]
        AliorBankSA,
        [Description("AarealBankAktiengesellschaftSpółkaAkcyjnaOddziałwPolsce")]
        AarealBankAktiengesellschaftSpółkaAkcyjnaOddziałwPolsce,
        [Description("CREDITSUISSELUXEMBOURGSASpółkaAkcyjnaOddziałwPolsce")]
        CREDITSUISSELUXEMBOURGSASpółkaAkcyjnaOddziałwPolsce,
        [Description("FMBankSA")]
        FMBankSA,
        [Description("CitibankEuropeplcPublicznaSpółkaAkcyjnaOddziałwPolsce")]
        CitibankEuropeplcPublicznaSpółkaAkcyjnaOddziałwPolsce,
        [Description("IkanoBankGmbHSpzooOddziałwPolsce")]
        IkanoBankGmbHSpzooOddziałwPolsce,
        [Description("NordeaBankABSAOddziałwPolsce")]
        NordeaBankABSAOddziałwPolsce,
        [Description("UBSLimitedspółkazograniczonąodpowiedzialnoąciąOddziałwPolsce")]
        UBSLimitedspółkazograniczonąodpowiedzialnoąciąOddziałwPolsce,
        [Description("JPMorganEuropeLimitedSpzooOddziałwPolsce")]
        JPMorganEuropeLimitedSpzooOddziałwPolsce,
        [Description("BankSpółdzielczywOtwocku")]
        BankSpółdzielczywOtwocku,
        [Description("BankSpółdzielczywPiasecznie")]
        BankSpółdzielczywPiasecznie,
        [Description("MazoviaBankSpółdzielczy")]
        MazoviaBankSpółdzielczy,
        [Description("BankSpółdzielczywRaszynie")]
        BankSpółdzielczywRaszynie,
        [Description("SpółdzielczyBankRzemiosłaiRolnictwa")]
        SpółdzielczyBankRzemiosłaiRolnictwa,
        [Description("BankSpółdzielczywTarczynie")]
        BankSpółdzielczywTarczynie,
        [Description("MazowieckiBankSpółdzielczywŁomiankach")]
        MazowieckiBankSpółdzielczywŁomiankach,
        [Description("BankSpółdzielczywNowymDworzeMazowieckim")]
        BankSpółdzielczywNowymDworzeMazowieckim,
        [Description("BankSpółdzielczywLegionowie")]
        BankSpółdzielczywLegionowie,
        [Description("WarszawskiBankSpółdzielczy")]
        WarszawskiBankSpółdzielczy,
        [Description("BankSpółdzielczywPruszkowie")]
        BankSpółdzielczywPruszkowie,
        [Description("BankSpółdzielczywNadarzynie")]
        BankSpółdzielczywNadarzynie,
        [Description("BankSpółdzielczywHalinowie")]
        BankSpółdzielczywHalinowie,
        [Description("BankSpółdzielczywLesznowoli")]
        BankSpółdzielczywLesznowoli,
        [Description("BankSpółdzielczywKarczewie")]
        BankSpółdzielczywKarczewie,
        [Description("BankSpółdzielczywBiałejPodlaskiej")]
        BankSpółdzielczywBiałejPodlaskiej,
        [Description("BankSpółdzielczywKonstantynowie")]
        BankSpółdzielczywKonstantynowie,
        [Description("BankSpółdzielczywKornicy")]
        BankSpółdzielczywKornicy,
        [Description("BankSpółdzielczywŁomazach")]
        BankSpółdzielczywŁomazach,
        [Description("BankSpółdzielczywMiędzyrzecuPodlaskim")]
        BankSpółdzielczywMiędzyrzecuPodlaskim,
        [Description("BankSpółdzielczywParczewie")]
        BankSpółdzielczywParczewie,
        [Description("BankSpółdzielczywPlaterowie")]
        BankSpółdzielczywPlaterowie,
        [Description("BankSpółdzielczywRadzyniuPodlaskim")]
        BankSpółdzielczywRadzyniuPodlaskim,
        [Description("BankSpółdzielczywSarnakach")]
        BankSpółdzielczywSarnakach,
        [Description("BankSpółdzielczywWisznicach")]
        BankSpółdzielczywWisznicach,
        [Description("BankSpółdzielczywBiałymstoku")]
        BankSpółdzielczywBiałymstoku,
        [Description("BankSpółdzielczywBielskuPodlaskim")]
        BankSpółdzielczywBielskuPodlaskim,
        [Description("BankSpółdzielczywBrańsku")]
        BankSpółdzielczywBrańsku,
        [Description("BankSpółdzielczywHajnówce")]
        BankSpółdzielczywHajnówce,
        [Description("BankSpółdzielczywJuchnowcuGórnym")]
        BankSpółdzielczywJuchnowcuGórnym,
        [Description("PodlaskiBankSpółdzielczywKnyszynie")]
        PodlaskiBankSpółdzielczywKnyszynie,
        [Description("BankSpółdzielczywKorycinie")]
        BankSpółdzielczywKorycinie,
        [Description("BankSpółdzielczywŁapach")]
        BankSpółdzielczywŁapach,
        [Description("BankSpółdzielczywMońkach")]
        BankSpółdzielczywMońkach,
        [Description("BankSpółdzielczywNarwi")]
        BankSpółdzielczywNarwi,
        [Description("BankSpółdzielczywSiemiatyczach")]
        BankSpółdzielczywSiemiatyczach,
        [Description("BankSpółdzielczywSokółce")]
        BankSpółdzielczywSokółce,
        [Description("BankSpółdzielczywSuchowoli")]
        BankSpółdzielczywSuchowoli,
        [Description("PodlaskoMazurskiBankSpółdzielczywZabłudowie")]
        PodlaskoMazurskiBankSpółdzielczywZabłudowie,
        [Description("ABSBankSpółdzielczy")]
        ABSBankSpółdzielczy,
        [Description("BeskidzkiBankSpółdzielczy")]
        BeskidzkiBankSpółdzielczy,
        [Description("BankSpółdzielczywBrzeźnicy")]
        BankSpółdzielczywBrzeźnicy,
        [Description("BankSpółdzielczywCieszynie")]
        BankSpółdzielczywCieszynie,
        [Description("BankSpółdzielczywJasienicy")]
        BankSpółdzielczywJasienicy,
        [Description("BankSpółdzielczywJeleśni")]
        BankSpółdzielczywJeleśni,
        [Description("BankSpółdzielczywKalwariiZebrzydowskiej")]
        BankSpółdzielczywKalwariiZebrzydowskiej,
        [Description("BankSpółdzielczywKętach")]
        BankSpółdzielczywKętach,
        [Description("BankSpółdzielczywPorąbce")]
        BankSpółdzielczywPorąbce,
        [Description("BankSpółdzielczywRajczy")]
        BankSpółdzielczywRajczy,
        [Description("BankSpółdzielczywSkoczowie")]
        BankSpółdzielczywSkoczowie,
        [Description("BankSpółdzielczywSuchejBeskidzkiej")]
        BankSpółdzielczywSuchejBeskidzkiej,
        [Description("BankSpółdzielczywUstroniu")]
        BankSpółdzielczywUstroniu,
        [Description("BankSpółdzielczywWęgierskiejGórce")]
        BankSpółdzielczywWęgierskiejGórce,
        [Description("BankSpółdzielczywBystrej")]
        BankSpółdzielczywBystrej,
        [Description("BankSpółdzielczywWilamowicach")]
        BankSpółdzielczywWilamowicach,
        [Description("BankSpółdzielczywZatorze")]
        BankSpółdzielczywZatorze,
        [Description("BankSpółdzielczywŻywcu")]
        BankSpółdzielczywŻywcu,
        [Description("BankSpółdzielczywRadziechowachWieprzu")]
        BankSpółdzielczywRadziechowachWieprzu,
        [Description("BankSpółdzielczywGilowicach")]
        BankSpółdzielczywGilowicach,
        [Description("BankSpółdzielczywBydgoszczy")]
        BankSpółdzielczywBydgoszczy,
        [Description("BankSpółdzielczywKoronowie")]
        BankSpółdzielczywKoronowie,
        [Description("BankSpółdzielczywChojnicach")]
        BankSpółdzielczywChojnicach,
        [Description("BankSpółdzielczywCzersku")]
        BankSpółdzielczywCzersku,
        [Description("BankSpółdzielczywInowrocławiu")]
        BankSpółdzielczywInowrocławiu,
        [Description("BankSpółdzielczywKruszwicy")]
        BankSpółdzielczywKruszwicy,
        [Description("BankSpółdzielczywStrzelnie")]
        BankSpółdzielczywStrzelnie,
        [Description("BankSpółdzielczywWięcborku")]
        BankSpółdzielczywWięcborku,
        [Description("BankSpółdzielczywSzubinie")]
        BankSpółdzielczywSzubinie,
        [Description("BankSpółdzielczywKcyni")]
        BankSpółdzielczywKcyni,
        [Description("BankSpółdzielczywBarcinie")]
        BankSpółdzielczywBarcinie,
        [Description("BankSpółdzielczywŚwieciu")]
        BankSpółdzielczywŚwieciu,
        [Description("BankSpółdzielczywOsiu")]
        BankSpółdzielczywOsiu,
        [Description("BankSpółdzielczywPruszczuPomorskim")]
        BankSpółdzielczywPruszczuPomorskim,
        [Description("BankSpółdzielczywNowemnWisłą")]
        BankSpółdzielczywNowemnWisłą,
        [Description("BankSpółdzielczywTucholi")]
        BankSpółdzielczywTucholi,
        [Description("BankSpółdzielczywNaklenNotecią")]
        BankSpółdzielczywNaklenNotecią,
        [Description("BankSpółdzielczyPałukiwŻninie")]
        BankSpółdzielczyPałukiwŻninie,
        [Description("PiastowskiBankSpółdzielczywJanikowie")]
        PiastowskiBankSpółdzielczywJanikowie,
        [Description("WschodniBankSpółdzielczywChełmie")]
        WschodniBankSpółdzielczywChełmie,
        [Description("BankSpółdzielczywWojsławicach")]
        BankSpółdzielczywWojsławicach,
        [Description("BankSpółdzielczywCycowie")]
        BankSpółdzielczywCycowie,
        [Description("BankSpółdzielczywSawinie")]
        BankSpółdzielczywSawinie,
        [Description("BankSpółdzielczywLeśniowicach")]
        BankSpółdzielczywLeśniowicach,
        [Description("BankSpółdzielczywKrasnymstawie")]
        BankSpółdzielczywKrasnymstawie,
        [Description("BankSpółdzielczywBiałopolu")]
        BankSpółdzielczywBiałopolu,
        [Description("BankSpółdzielczywBieżuniu")]
        BankSpółdzielczywBieżuniu,
        [Description("PolskiBankSpółdzielczywCiechanowie")]
        PolskiBankSpółdzielczywCiechanowie,
        [Description("BankSpółdzielczywDziałdowiezsiedzibąwLidzbarku")]
        BankSpółdzielczywDziałdowiezsiedzibąwLidzbarku,
        [Description("BankSpółdzielczywGąsocinie")]
        BankSpółdzielczywGąsocinie,
        [Description("BankSpółdzielczywGrudusku")]
        BankSpółdzielczywGrudusku,
        [Description("BankSpłŁodzielczywMławie")]
        BankSpłŁodzielczywMławie,
        [Description("BankSpółdzielczywNasielsku")]
        BankSpółdzielczywNasielsku,
        [Description("BankSpółdzielczywGlinojecku")]
        BankSpółdzielczywGlinojecku,
        [Description("BankSpółdzielczywPłońsku")]
        BankSpółdzielczywPłońsku,
        [Description("BankSpółdzielczywPułtusku")]
        BankSpółdzielczywPułtusku,
        [Description("BankSpółdzielczywRaciążu")]
        BankSpółdzielczywRaciążu,
        [Description("BankSpółdzielczywStrzegowie")]
        BankSpółdzielczywStrzegowie,
        [Description("BankSpółdzielczywZałuskach")]
        BankSpółdzielczywZałuskach,
        [Description("BankSpółdzielczywŻurominie")]
        BankSpółdzielczywŻurominie,
        [Description("BankSpółdzielczywKłobucku")]
        BankSpółdzielczywKłobucku,
        [Description("BankSpółdzielczyweWręczycyWielkiej")]
        BankSpółdzielczyweWręczycyWielkiej,
        [Description("BankSpółdzielczywKrzepicach")]
        BankSpółdzielczywKrzepicach,
        [Description("SpółdzielczyBankLudowyRzemiosłaiUsługwCzęstochowieogłoszonaupadłość140295")]
        SpółdzielczyBankLudowyRzemiosłaiUsługwCzęstochowieogłoszonaupadłość140295,
        [Description("BankSpółdzielczyweMstowie")]
        BankSpółdzielczyweMstowie,
        [Description("BankSpółdzielczywMykanowie")]
        BankSpółdzielczywMykanowie,
        [Description("BankSpółdzielczywPopowiezswZawadach")]
        BankSpółdzielczywPopowiezswZawadach,
        [Description("BankSpółdzielczywPoczesnej")]
        BankSpółdzielczywPoczesnej,
        [Description("BankSpółdzielczywKłomnicach")]
        BankSpółdzielczywKłomnicach,
        [Description("BankSpółdzielczywPającznie")]
        BankSpółdzielczywPającznie,
        [Description("BankSpółdzielczywŻytnie")]
        BankSpółdzielczywŻytnie,
        [Description("BankSpółdzielczywPraszce")]
        BankSpółdzielczywPraszce,
        [Description("BankSpółdzielczywKonopiskach")]
        BankSpółdzielczywKonopiskach,
        [Description("BankSpółdzielczywKoniecpolu")]
        BankSpółdzielczywKoniecpolu,
        [Description("BankSpółdzielczywSzczekocinach")]
        BankSpółdzielczywSzczekocinach,
        [Description("MiędzypowiatowyBankSpółdzielczywMyszkowie")]
        MiędzypowiatowyBankSpółdzielczywMyszkowie,
        [Description("BankSpółdzielczywKoszęcinie")]
        BankSpółdzielczywKoszęcinie,
        [Description("SPÓŁDZIELCZYBANKLUDOWYwELBLĄGU")]
        SPÓŁDZIELCZYBANKLUDOWYwELBLĄGU,
        [Description("PowiślańskiBankSpółdzielczywKwidzynie")]
        PowiślańskiBankSpółdzielczywKwidzynie,
        [Description("BankSpółdzielczywMalborku")]
        BankSpółdzielczywMalborku,
        [Description("BankSpółdzielczywNowymStawie")]
        BankSpółdzielczywNowymStawie,
        [Description("ŻuławskiBankSpółdzielczy")]
        ŻuławskiBankSpółdzielczy,
        [Description("BankSpółdzielczywStegnie")]
        BankSpółdzielczywStegnie,
        [Description("BankSpółdzielczywSztumie")]
        BankSpółdzielczywSztumie,
        [Description("BankSpółdzielczywDzierzgoniu")]
        BankSpółdzielczywDzierzgoniu,
        [Description("BraniewskoPasłęckiBankSpółdzielczyzsiedzibąwPasłęku")]
        BraniewskoPasłęckiBankSpółdzielczyzsiedzibąwPasłęku,
        [Description("BankSpółdzielczywPrabutach")]
        BankSpółdzielczywPrabutach,
        [Description("BankSpółdzielczywSuszu")]
        BankSpółdzielczywSuszu,
        [Description("BankSpółdzielczywSierakowicach")]
        BankSpółdzielczywSierakowicach,
        [Description("BankSpółdzielczywKościerzynie")]
        BankSpółdzielczywKościerzynie,
        [Description("BankSpółdzielczywPruszczuGdańskim")]
        BankSpółdzielczywPruszczuGdańskim,
        [Description("BankSpółdzielczywPszczółkach")]
        BankSpółdzielczywPszczółkach,
        [Description("BankSpółdzielczywStarogardzieGdańskim")]
        BankSpółdzielczywStarogardzieGdańskim,
        [Description("BankSpółdzielczywLubichowie")]
        BankSpółdzielczywLubichowie,
        [Description("BankSpółdzielczywSkórczu")]
        BankSpółdzielczywSkórczu,
        [Description("BankSpółdzielczywSmętowieGranicznym")]
        BankSpółdzielczywSmętowieGranicznym,
        [Description("BankSpółdzielczywTczewie")]
        BankSpółdzielczywTczewie,
        [Description("BankSpółdzielczywGniewie")]
        BankSpółdzielczywGniewie,
        [Description("BankSpółdzielczywPucku")]
        BankSpółdzielczywPucku,
        [Description("BankSpółdzielczywKrokowej")]
        BankSpółdzielczywKrokowej,
        [Description("KaszubskiBankSpółdzielczywWejherowie")]
        KaszubskiBankSpółdzielczywWejherowie,
        [Description("BankRumiaSpółdzielczy")]
        BankRumiaSpółdzielczy,
        [Description("GospodarczyBankSpółdzielczywBarlinku")]
        GospodarczyBankSpółdzielczywBarlinku,
        [Description("GospodarczyBankSpółdzielczywChoszcznie")]
        GospodarczyBankSpółdzielczywChoszcznie,
        [Description("LubuskoWielkopolskiBankSpółdzielczyzsiedzibąwDrezdenku")]
        LubuskoWielkopolskiBankSpółdzielczyzsiedzibąwDrezdenku,
        [Description("GospodarczyBankSpółdzielczywGorzowieWielkopolskim")]
        GospodarczyBankSpółdzielczywGorzowieWielkopolskim,
        [Description("GospodarczyBankSpółdzielczyMiędzyrzecz")]
        GospodarczyBankSpółdzielczyMiędzyrzecz,
        [Description("BankSpółdzielczywOśnieLubuskim")]
        BankSpółdzielczywOśnieLubuskim,
        [Description("BankSpółdzielczywRzepinie")]
        BankSpółdzielczywRzepinie,
        [Description("BankSpółdzielczywSantoku")]
        BankSpółdzielczywSantoku,
        [Description("BankSpółdzielczywPieńsku")]
        BankSpółdzielczywPieńsku,
        [Description("BankSpółdzielczyLwówekŚląskiwLwówkuŚląskim")]
        BankSpółdzielczyLwówekŚląskiwLwówkuŚląskim,
        [Description("użyckiBankSpółdzielczywLubaniu")]
        użyckiBankSpółdzielczywLubaniu,
        [Description("BankSpółdzielczywKamiennejGórze")]
        BankSpółdzielczywKamiennejGórze,
        [Description("BankSpółdzielczyZiemiKaliskiej")]
        BankSpółdzielczyZiemiKaliskiej,
        [Description("BankSpółdzielczywPleszewie")]
        BankSpółdzielczywPleszewie,
        [Description("BankSpółdzielczywDobrzycy")]
        BankSpółdzielczywDobrzycy,
        [Description("BankSpółdzielczywKrotoszynie")]
        BankSpółdzielczywKrotoszynie,
        [Description("SpółdzielczyBankLudowywKępnie")]
        SpółdzielczyBankLudowywKępnie,
        [Description("BankSpółdzielczywJarocinie")]
        BankSpółdzielczywJarocinie,
        [Description("BankSpółdzielczywRaszkowie")]
        BankSpółdzielczywRaszkowie,
        [Description("SpółdzielczyBankLudowywSkalmierzycach")]
        SpółdzielczyBankLudowywSkalmierzycach,
        [Description("BankSpółdzielczywTychach")]
        BankSpółdzielczywTychach,
        [Description("MikołowskiBankSpółdzielczywMikołowie")]
        MikołowskiBankSpółdzielczywMikołowie,
        [Description("ŚląskiBankSpółdzielczySilesiawKatowicach")]
        ŚląskiBankSpółdzielczySilesiawKatowicach,
        [Description("BankSpółdzielczywBędzinie")]
        BankSpółdzielczywBędzinie,
        [Description("BankSpółdzielczywSiewierzu")]
        BankSpółdzielczywSiewierzu,
        [Description("BankSpółdzielczywZawierciu")]
        BankSpółdzielczywZawierciu,
        [Description("BankSpółdzielczywMierzęcicach")]
        BankSpółdzielczywMierzęcicach,
        [Description("BankSpółdzielczywChrzanowie")]
        BankSpółdzielczywChrzanowie,
        [Description("BankSpółdzielczywJaworznie")]
        BankSpółdzielczywJaworznie,
        [Description("BankSpółdzielczywMiedźnej")]
        BankSpółdzielczywMiedźnej,
        [Description("BankSpółdzielczywPawłowicach")]
        BankSpółdzielczywPawłowicach,
        [Description("BankSpółdzielczywPszczynie")]
        BankSpółdzielczywPszczynie,
        [Description("BankSpółdzielczywWolbromiu")]
        BankSpółdzielczywWolbromiu,
        [Description("BankSpółdzielczyCzechowiceDziedziceBestwina")]
        BankSpółdzielczyCzechowiceDziedziceBestwina,
        [Description("OrzeskoKnurowskiBankSpółdzielczyzsiedzibąwKnurowie")]
        OrzeskoKnurowskiBankSpółdzielczyzsiedzibąwKnurowie,
        [Description("BankSpółdzielczywRybniku")]
        BankSpółdzielczywRybniku,
        [Description("BankSpółdzielczywŻorach")]
        BankSpółdzielczywŻorach,
        [Description("BankSpółdzielczywGliwicach")]
        BankSpółdzielczywGliwicach,
        [Description("BankSpółdzielczywSośnicowicach")]
        BankSpółdzielczywSośnicowicach,
        [Description("BankSpółdzielczywTarnowskichGórach")]
        BankSpółdzielczywTarnowskichGórach,
        [Description("BankSpółdzielczywTworogu")]
        BankSpółdzielczywTworogu,
        [Description("BankSpółdzielczywŚwierklańcu")]
        BankSpółdzielczywŚwierklańcu,
        [Description("BankSpółdzielczywWodzisławiuŚląskim")]
        BankSpółdzielczywWodzisławiuŚląskim,
        [Description("BankSpółdzielczywGorzycach")]
        BankSpółdzielczywGorzycach,
        [Description("BankSpółdzielczywJastrzębiuZdroju")]
        BankSpółdzielczywJastrzębiuZdroju,
        [Description("BankSpółdzielczyBytom")]
        BankSpółdzielczyBytom,
        [Description("BankSpółdzielczywKrzyżanowicach")]
        BankSpółdzielczywKrzyżanowicach,
        [Description("BankSpółdzielczywRaciborzu")]
        BankSpółdzielczywRaciborzu,
        [Description("BankSpółdzielczywBuskuZdroju")]
        BankSpółdzielczywBuskuZdroju,
        [Description("BankSpółdzielczywChmielniku")]
        BankSpółdzielczywChmielniku,
        [Description("BankSpółdzielczyDaleszyceGórno")]
        BankSpółdzielczyDaleszyceGórno,
        [Description("BankSpółdzielczywJędrzejowie")]
        BankSpółdzielczywJędrzejowie,
        [Description("BankSpółdzielczywKielcach")]
        BankSpółdzielczywKielcach,
        [Description("BankSpółdzielczywKońskich")]
        BankSpółdzielczywKońskich,
        [Description("BankSpółdzielczywopusznie")]
        BankSpółdzielczywopusznie,
        [Description("BankSpółdzielczywOstrowcuŚwiętokrzyskim")]
        BankSpółdzielczywOstrowcuŚwiętokrzyskim,
        [Description("BankSpółdzielczywPińczowie")]
        BankSpółdzielczywPińczowie,
        [Description("BankSpółdzielczywSamsonowie")]
        BankSpółdzielczywSamsonowie,
        [Description("BankSpółdzielczywSędziszowie")]
        BankSpółdzielczywSędziszowie,
        [Description("NadwiślańskiBankSpółdzielczywSolcuZdroju")]
        NadwiślańskiBankSpółdzielczywSolcuZdroju,
        [Description("BankSpółdzielczywStarachowicach")]
        BankSpółdzielczywStarachowicach,
        [Description("BankSpółdzielczywStopnicy")]
        BankSpółdzielczywStopnicy,
        [Description("BankSpółdzielczywSuchedniowie")]
        BankSpółdzielczywSuchedniowie,
        [Description("BankSpółdzielczywSzydłowie")]
        BankSpółdzielczywSzydłowie,
        [Description("BankSpółdzielczywWąchocku")]
        BankSpółdzielczywWąchocku,
        [Description("BankSpółdzielczyweWłoszczowie")]
        BankSpółdzielczyweWłoszczowie,
        [Description("BankSpółdzielczywWodzisławiu")]
        BankSpółdzielczywWodzisławiu,
        [Description("BankSpółdzielczywKoninie")]
        BankSpółdzielczywKoninie,
        [Description("BankSpółdzielczywŚlesinie")]
        BankSpółdzielczywŚlesinie,
        [Description("BankSpółdzielczywWitkowie")]
        BankSpółdzielczywWitkowie,
        [Description("BankSpółdzielczywGrabowie")]
        BankSpółdzielczywGrabowie,
        [Description("BankSpółdzielczywSłupcy")]
        BankSpółdzielczywSłupcy,
        [Description("LudowyBankSpółdzielczywStrzałkowie")]
        LudowyBankSpółdzielczywStrzałkowie,
        [Description("BankSpółdzielczywZagórowie")]
        BankSpółdzielczywZagórowie,
        [Description("BankSpółdzielczywKłodawie")]
        BankSpółdzielczywKłodawie,
        [Description("RejonowyBankSpółdzielczywMalanowie")]
        RejonowyBankSpółdzielczywMalanowie,
        [Description("BankSpółdzielczywWierzbinku")]
        BankSpółdzielczywWierzbinku,
        [Description("BankSpółdzielczywBiałogardzie")]
        BankSpółdzielczywBiałogardzie,
        [Description("BałtyckiBankSpółdzielczy")]
        BałtyckiBankSpółdzielczy,
        [Description("BankSpółdzielczywKaliszuPomorskim")]
        BankSpółdzielczywKaliszuPomorskim,
        [Description("BankSpółdzielczywPołczynieZdroju")]
        BankSpółdzielczywPołczynieZdroju,
        [Description("PomorskiBankSpółdzielczy")]
        PomorskiBankSpółdzielczy,
        [Description("BankSpółdzielczyRzemiosławKrakowie")]
        BankSpółdzielczyRzemiosławKrakowie,
        [Description("KrakowskiBankSpółdzielczy")]
        KrakowskiBankSpółdzielczy,
        [Description("BankSpółdzielczywProszowicach")]
        BankSpółdzielczywProszowicach,
        [Description("BankSpółdzielczywSkawinie")]
        BankSpółdzielczywSkawinie,
        [Description("BankSpółdzielczywDobczycach")]
        BankSpółdzielczywDobczycach,
        [Description("BankSpółdzielczywKrzeszowicach")]
        BankSpółdzielczywKrzeszowicach,
        [Description("BankSpółdzielczywSłomnikach")]
        BankSpółdzielczywSłomnikach,
        [Description("MałopolskiBankSpółdzielczywWieliczce")]
        MałopolskiBankSpółdzielczywWieliczce,
        [Description("BieszczadzkiBankSpółdzielczywUstrzykachDolnych")]
        BieszczadzkiBankSpółdzielczywUstrzykachDolnych,
        [Description("BankSpółdzielczywKołaczycach")]
        BankSpółdzielczywKołaczycach,
        [Description("BankSpółdzielczywBieczu")]
        BankSpółdzielczywBieczu,
        [Description("BankSpółdzielczywLipinkach")]
        BankSpółdzielczywLipinkach,
        [Description("BankSpółdzielczywRymanowie")]
        BankSpółdzielczywRymanowie,
        [Description("PodkarpackiBankSpółdzielczy")]
        PodkarpackiBankSpółdzielczy,
        [Description("BankSpółdzielczywChojnowie")]
        BankSpółdzielczywChojnowie,
        [Description("BankSpółdzielczywGłogowie")]
        BankSpółdzielczywGłogowie,
        [Description("BankSpółdzielczywJaworze")]
        BankSpółdzielczywJaworze,
        [Description("BankSpółdzielczywLegnicy")]
        BankSpółdzielczywLegnicy,
        [Description("BankSpółdzielczywPrzemkowie")]
        BankSpółdzielczywPrzemkowie,
        [Description("PowiatowyBankSpółdzielczywZłotoryi")]
        PowiatowyBankSpółdzielczywZłotoryi,
        [Description("BankSpółdzielczyweWłoszakowicach")]
        BankSpółdzielczyweWłoszakowicach,
        [Description("BankSpółdzielczywGórze")]
        BankSpółdzielczywGórze,
        [Description("BankSpółdzielczywKościanie")]
        BankSpółdzielczywKościanie,
        [Description("BankSpółdzielczywŚmiglu")]
        BankSpółdzielczywŚmiglu,
        [Description("BankSpółdzielczyweWschowie")]
        BankSpółdzielczyweWschowie,
        [Description("BankSpółdzielczywJutrosinie")]
        BankSpółdzielczywJutrosinie,
        [Description("PowiatowyBankSpółdzielczywGostyniu")]
        PowiatowyBankSpółdzielczywGostyniu,
        [Description("BankSpółdzielczywPoniecu")]
        BankSpółdzielczywPoniecu,
        [Description("RejonowyBankSpółdzielczywBychawie")]
        RejonowyBankSpółdzielczywBychawie,
        [Description("BankSpółdzielczywNiedrzwicyDużej")]
        BankSpółdzielczywNiedrzwicyDużej,
        [Description("SpółdzielczyBankPowiatowywPiaskach")]
        SpółdzielczyBankPowiatowywPiaskach,
        [Description("BankSpółdzielczywŁęcznej")]
        BankSpółdzielczywŁęcznej,
        [Description("BankSpółdzielczywNiemcach")]
        BankSpółdzielczywNiemcach,
        [Description("BankSpółdzielczywLubartowie")]
        BankSpółdzielczywLubartowie,
        [Description("BankSpółdzielczyZiemiKraśnickiejwKraśniku")]
        BankSpółdzielczyZiemiKraśnickiejwKraśniku,
        [Description("BankSpółdzielczywKocku")]
        BankSpółdzielczywKocku,
        [Description("BankSpółdzielczywRykach")]
        BankSpółdzielczywRykach,
        [Description("BankSpółdzielczywJózefowienadWisłą")]
        BankSpółdzielczywJózefowienadWisłą,
        [Description("BankSpółdzielczywKazimierzuDolnym")]
        BankSpółdzielczywKazimierzuDolnym,
        [Description("BankSpółdzielczywKurowie")]
        BankSpółdzielczywKurowie,
        [Description("BankSpółdzielczywNałęczowie")]
        BankSpółdzielczywNałęczowie,
        [Description("PowiatowyBankSpółdzielczywOpoluLubelskim")]
        PowiatowyBankSpółdzielczywOpoluLubelskim,
        [Description("BankSpółdzielczywPoniatowej")]
        BankSpółdzielczywPoniatowej,
        [Description("NadwiślańskiBankSpółdzielczywPuławach")]
        NadwiślańskiBankSpółdzielczywPuławach,
        [Description("BankSpółdzielczywKońskowoli")]
        BankSpółdzielczywKońskowoli,
        [Description("BankSpółdzielczywCzyżewie")]
        BankSpółdzielczywCzyżewie,
        [Description("BankSpółdzielczywCiechanowcu")]
        BankSpółdzielczywCiechanowcu,
        [Description("BankSpółdzielczywJedwabnem")]
        BankSpółdzielczywJedwabnem,
        [Description("BankSpółdzielczywKolnie")]
        BankSpółdzielczywKolnie,
        [Description("BankSpółdzielczywŁomży")]
        BankSpółdzielczywŁomży,
        [Description("BankSpółdzielczywŁomży1")]
        BankSpółdzielczywŁomży1,
        [Description("HexaBankSpółdzielczy")]
        HexaBankSpółdzielczy,
        [Description("BankSpółdzielczywSokołach")]
        BankSpółdzielczywSokołach,
        [Description("BankSpółdzielczywSzczuczynie")]
        BankSpółdzielczywSzczuczynie,
        [Description("SpółdzielczyBankRozwoju")]
        SpółdzielczyBankRozwoju,
        [Description("BankSpółdzielczywSzumowie")]
        BankSpółdzielczywSzumowie,
        [Description("BankSpółdzielczywWysokiemMazowieckiem")]
        BankSpółdzielczywWysokiemMazowieckiem,
        [Description("BankSpółdzielczywZambrowie")]
        BankSpółdzielczywZambrowie,
        [Description("BankSpółdzielczywAleksandrowieódzkim")]
        BankSpółdzielczywAleksandrowieódzkim,
        [Description("BankSpółdzielczywAndrespolu")]
        BankSpółdzielczywAndrespolu,
        [Description("BankSpółdzielczywZgierzu")]
        BankSpółdzielczywZgierzu,
        [Description("BankSpółdzielczyRzemiosławodzi")]
        BankSpółdzielczyRzemiosławodzi,
        [Description("BankSpółdzielczywStrykowie")]
        BankSpółdzielczywStrykowie,
        [Description("BankSpółdzielczywOzorkowie")]
        BankSpółdzielczywOzorkowie,
        [Description("BankSpółdzielczywGłownie")]
        BankSpółdzielczywGłownie,
        [Description("BankSpółdzielczyTowarzystwoOszczędnościowoPożyczkowePACOBANKwPabianicach")]
        BankSpółdzielczyTowarzystwoOszczędnościowoPożyczkowePACOBANKwPabianicach,
        [Description("TatrzańskiBankSpółdzielczy")]
        TatrzańskiBankSpółdzielczy,
        [Description("BankSpółdzielczywCzarnymDunajcu")]
        BankSpółdzielczywCzarnymDunajcu,
        [Description("BankSpółdzielczywGorlicach")]
        BankSpółdzielczywGorlicach,
        [Description("BankSpółdzielczywGrybowie")]
        BankSpółdzielczywGrybowie,
        [Description("BankSpółdzielczywJabłonce")]
        BankSpółdzielczywJabłonce,
        [Description("BankSpółdzielczywJordanowie")]
        BankSpółdzielczywJordanowie,
        [Description("BankSpółdzielczywLimanowej")]
        BankSpółdzielczywLimanowej,
        [Description("ŁąckiBankSpółdzielczy")]
        ŁąckiBankSpółdzielczy,
        [Description("BankSpółdzielczywMszanieDolnej")]
        BankSpółdzielczywMszanieDolnej,
        [Description("BankSpółdzielczyMuszynaKrynicaZdrój")]
        BankSpółdzielczyMuszynaKrynicaZdrój,
        [Description("BankSpółdzielczywNawojowej")]
        BankSpółdzielczywNawojowej,
        [Description("BankSpółdzielczywNowymSączu")]
        BankSpółdzielczywNowymSączu,
        [Description("BankSpółdzielczywNowymTargu")]
        BankSpółdzielczywNowymTargu,
        [Description("BankSpółdzielczywPiwnicznejZdroju")]
        BankSpółdzielczywPiwnicznejZdroju,
        [Description("BankSpółdzielczywPodegrodziu")]
        BankSpółdzielczywPodegrodziu,
        [Description("BankSpółdzielczywRabieWyżnej")]
        BankSpółdzielczywRabieWyżnej,
        [Description("BankSpółdzielczywStarymSączu")]
        BankSpółdzielczywStarymSączu,
        [Description("BankSpółdzielczywKrościenkunD")]
        BankSpółdzielczywKrościenkunD,
        [Description("BankSpółdzielczywososinieDolnej")]
        BankSpółdzielczywososinieDolnej,
        [Description("PodhalańskiBankSpółdzielczywZakopanem")]
        PodhalańskiBankSpółdzielczywZakopanem,
        [Description("BankSpółdzielczywOlsztynku")]
        BankSpółdzielczywOlsztynku,
        [Description("BankSpółdzielczywIławie")]
        BankSpółdzielczywIławie,
        [Description("BankSpółdzielczywLubawie")]
        BankSpółdzielczywLubawie,
        [Description("BankSpółdzielczywNidzicy")]
        BankSpółdzielczywNidzicy,
        [Description("BankSpółdzielczywSzczytnie")]
        BankSpółdzielczywSzczytnie,
        [Description("MorąskoZalewskiBankSpółdzielczywZalewie")]
        MorąskoZalewskiBankSpółdzielczywZalewie,
        [Description("BankSpółdzielczywMrągowie")]
        BankSpółdzielczywMrągowie,
        [Description("BankSpółdzielczywReszlu")]
        BankSpółdzielczywReszlu,
        [Description("BankSpółdzielczywBartoszycach")]
        BankSpółdzielczywBartoszycach,
        [Description("WarmińskiBankSpółdzielczy")]
        WarmińskiBankSpółdzielczy,
        [Description("SpółdzielczyBankLudowywOlsztynie")]
        SpółdzielczyBankLudowywOlsztynie,
        [Description("BankSpółdzielczywBrzegu")]
        BankSpółdzielczywBrzegu,
        [Description("BankSpółdzielczywBaborowie")]
        BankSpółdzielczywBaborowie,
        [Description("BankSpółdzielczywBranicach")]
        BankSpółdzielczywBranicach,
        [Description("BankSpółdzielczywGłubczycach")]
        BankSpółdzielczywGłubczycach,
        [Description("BankSpółdzielczyGrodkówosiówzsiedzibąwGrodkowie")]
        BankSpółdzielczyGrodkówosiówzsiedzibąwGrodkowie,
        [Description("BankSpółdzielczywOtmuchowie")]
        BankSpółdzielczywOtmuchowie,
        [Description("BankSpółdzielczywWołczynie")]
        BankSpółdzielczywWołczynie,
        [Description("PowiatowyBankSpółdzielczywKędzierzynieKoźlu")]
        PowiatowyBankSpółdzielczywKędzierzynieKoźlu,
        [Description("BankSpółdzielczywGogolinie")]
        BankSpółdzielczywGogolinie,
        [Description("BankSpółdzielczywKrapkowicach")]
        BankSpółdzielczywKrapkowicach,
        [Description("BankSpółdzielczywNamysłowie")]
        BankSpółdzielczywNamysłowie,
        [Description("BankSpółdzielczywGłuchołazach")]
        BankSpółdzielczywGłuchołazach,
        [Description("BankSpółdzielczywDobrzeniuWielkim")]
        BankSpółdzielczywDobrzeniuWielkim,
        [Description("BankSpółdzielczywubnianach")]
        BankSpółdzielczywubnianach,
        [Description("BankSpółdzielczyBankRolnikówwOpolu")]
        BankSpółdzielczyBankRolnikówwOpolu,
        [Description("BankSpółdzielczywBiałej")]
        BankSpółdzielczywBiałej,
        [Description("BankSpółdzielczywGłogówku")]
        BankSpółdzielczywGłogówku,
        [Description("BankSpółdzielczywPrudniku")]
        BankSpółdzielczywPrudniku,
        [Description("BankSpółdzielczywLeśnicy")]
        BankSpółdzielczywLeśnicy,
        [Description("BankSpółdzielczywZawadzkiem")]
        BankSpółdzielczywZawadzkiem,
        [Description("BankSpółdzielczywChorzelach")]
        BankSpółdzielczywChorzelach,
        [Description("BankSpółdzielczywGoworowie")]
        BankSpółdzielczywGoworowie,
        [Description("BankSpółdzielczywKadzidle")]
        BankSpółdzielczywKadzidle,
        [Description("BankSpółdzielczywKrasnosielcu")]
        BankSpółdzielczywKrasnosielcu,
        [Description("BankSpółdzielczywMyszyńcu")]
        BankSpółdzielczywMyszyńcu,
        [Description("BankSpółdzielczywOstrołęce")]
        BankSpółdzielczywOstrołęce,
        [Description("BankSpółdzielczywOstrowiMazowieckiej")]
        BankSpółdzielczywOstrowiMazowieckiej,
        [Description("BankSpółdzielczywPrzasnyszu")]
        BankSpółdzielczywPrzasnyszu,
        [Description("BankSpółdzielczywRóżanie")]
        BankSpółdzielczywRóżanie,
        [Description("BankSpółdzielczywWąsewie")]
        BankSpółdzielczywWąsewie,
        [Description("PolskiBankSpółdzielczywWyszkowie")]
        PolskiBankSpółdzielczywWyszkowie,
        [Description("BankSpółdzielczywJastrowiu")]
        BankSpółdzielczywJastrowiu,
        [Description("NadnoteckiBankSpółdzielczy")]
        NadnoteckiBankSpółdzielczy,
        [Description("BankSpółdzielczywŁobżenicy")]
        BankSpółdzielczywŁobżenicy,
        [Description("BankSpółdzielczywWysokiej")]
        BankSpółdzielczywWysokiej,
        [Description("SpółdzielczyBankLudowywZłotowie")]
        SpółdzielczyBankLudowywZłotowie,
        [Description("BankSpółdzielczywLipce")]
        BankSpółdzielczywLipce,
        [Description("SpółdzielczyBankLudowywZakrzewie")]
        SpółdzielczyBankLudowywZakrzewie,
        [Description("BankSpółdzielczywChodzieży")]
        BankSpółdzielczywChodzieży,
        [Description("BankSpółdzielczywCzarnkowie")]
        BankSpółdzielczywCzarnkowie,
        [Description("PałuckiBankSpółdzielczywWągrowcu")]
        PałuckiBankSpółdzielczywWągrowcu,
        [Description("BankSpółdzielczywWieleniu")]
        BankSpółdzielczywWieleniu,
        [Description("BankSpółdzielczyweWronkach")]
        BankSpółdzielczyweWronkach,
        [Description("BankSpółdzielczywBełchatowie")]
        BankSpółdzielczywBełchatowie,
        [Description("BankSpółdzielczyZiemiPiotrkowskiejwPiotrkowieTrybunalskim")]
        BankSpółdzielczyZiemiPiotrkowskiejwPiotrkowieTrybunalskim,
        [Description("BankSpółdzielczywKleszczowie")]
        BankSpółdzielczywKleszczowie,
        [Description("ESBANKBankSpółdzielczy")]
        ESBANKBankSpółdzielczy,
        [Description("PowiatowyBankSpółdzielczywTomaszowieMazowieckim")]
        PowiatowyBankSpółdzielczywTomaszowieMazowieckim,
        [Description("BankSpółdzielczywPrzedborzu")]
        BankSpółdzielczywPrzedborzu,
        [Description("BankSpółdzielczywOpocznie")]
        BankSpółdzielczywOpocznie,
        [Description("BankSpółdzielczywMałejWsi")]
        BankSpółdzielczywMałejWsi,
        [Description("BankSpółdzielczywStaroźrebach")]
        BankSpółdzielczywStaroźrebach,
        [Description("BankSpółdzielczywIłowie")]
        BankSpółdzielczywIłowie,
        [Description("NadwiślańskiBankSpółdzielczywCzerwińskunadWisłązsiedzibąwWyszogrodzie")]
        NadwiślańskiBankSpółdzielczywCzerwińskunadWisłązsiedzibąwWyszogrodzie,
        [Description("BankSpółdzielczywGostyninie")]
        BankSpółdzielczywGostyninie,
        [Description("BankSpółdzielczywGąbinie")]
        BankSpółdzielczywGąbinie,
        [Description("BankSpółdzielczywSierpcu")]
        BankSpółdzielczywSierpcu,
        [Description("BankSpółdzielczyWspólnaPracawKutnie")]
        BankSpółdzielczyWspólnaPracawKutnie,
        [Description("BankSpółdzielczywŻychlinie")]
        BankSpółdzielczywŻychlinie,
        [Description("BankSpółdzielczywKrośniewicach")]
        BankSpółdzielczywKrośniewicach,
        [Description("BankSpółdzielczyZiemiŁęczyckiejwŁęczycy")]
        BankSpółdzielczyZiemiŁęczyckiejwŁęczycy,
        [Description("BankSpółdzielczywStrzelcach")]
        BankSpółdzielczywStrzelcach,
        [Description("BankSpółdzielczywStarejBiałej")]
        BankSpółdzielczywStarejBiałej,
        [Description("BankSpółdzielczyMAZOWSZEwPłocku")]
        BankSpółdzielczyMAZOWSZEwPłocku,
        [Description("POZNAŃSKIBANKSPÓDZIELCZY")]
        POZNAŃSKIBANKSPÓDZIELCZY,
        [Description("PobiedziskoGoślińskiBankSpółdzielczywPobiedziskach")]
        PobiedziskoGoślińskiBankSpółdzielczywPobiedziskach,
        [Description("GospodarczyBankSpółdzielczywMosinie")]
        GospodarczyBankSpółdzielczywMosinie,
        [Description("LudowyBankSpółdzielczywObornikach")]
        LudowyBankSpółdzielczywObornikach,
        [Description("BankSpółdzielczywNowymTomyślu")]
        BankSpółdzielczywNowymTomyślu,
        [Description("BankSpółdzielczywGrodziskuWielkopolskim")]
        BankSpółdzielczywGrodziskuWielkopolskim,
        [Description("BankSpółdzielczywGnieźnie")]
        BankSpółdzielczywGnieźnie,
        [Description("WielkopolskiBankSpółdzielczy")]
        WielkopolskiBankSpółdzielczy,
        [Description("BankSpółdzielczyDuszniki")]
        BankSpółdzielczyDuszniki,
        [Description("BankSpółdzielczywKostrzynie")]
        BankSpółdzielczywKostrzynie,
        [Description("BankSpółdzielczywKórniku")]
        BankSpółdzielczywKórniku,
        [Description("NadobrzańskiBankSpółdzielczywRakoniewicach")]
        NadobrzańskiBankSpółdzielczywRakoniewicach,
        [Description("BankSpółdzielczyPojezierzaMiędzychodzkoSierakowskiegowSierakowie")]
        BankSpółdzielczyPojezierzaMiędzychodzkoSierakowskiegowSierakowie,
        [Description("SpółdzielczyBankLudowyimKsPWawrzyniaka")]
        SpółdzielczyBankLudowyimKsPWawrzyniaka,
        [Description("BANKSPÓŁDZIELCZYwŚrodzieWielkopolskiej")]
        BANKSPÓŁDZIELCZYwŚrodzieWielkopolskiej,
        [Description("BankSpółdzielczywChłopicach")]
        BankSpółdzielczywChłopicach,
        [Description("BankSpółdzielczywDynowie")]
        BankSpółdzielczywDynowie,
        [Description("BankSpółdzielczywStarymDzikowie")]
        BankSpółdzielczywStarymDzikowie,
        [Description("BankSpółdzielczywJarosławiu")]
        BankSpółdzielczywJarosławiu,
        [Description("PowiatowyBankSpółdzielczywLubaczowie")]
        PowiatowyBankSpółdzielczywLubaczowie,
        [Description("BankSpółdzielczywNarolu")]
        BankSpółdzielczywNarolu,
        [Description("BankSpółdzielczywPruchnikuukończonepostępowupadłościowe")]
        BankSpółdzielczywPruchnikuukończonepostępowupadłościowe,
        [Description("BankSpółdzielczywPrzeworsku")]
        BankSpółdzielczywPrzeworsku,
        [Description("BankSpółdzielczywRadymnie")]
        BankSpółdzielczywRadymnie,
        [Description("BankSpółdzielczywRoźwienicy")]
        BankSpółdzielczywRoźwienicy,
        [Description("BankSpółdzielczywŻurawicy")]
        BankSpółdzielczywŻurawicy,
        [Description("BankSpółdzielczyRzemiosławRadomiu")]
        BankSpółdzielczyRzemiosławRadomiu,
        [Description("BankSpółdzielczyimStefczykawBelskuDużym")]
        BankSpółdzielczyimStefczykawBelskuDużym,
        [Description("BankSpółdzielczywBiałobrzegach")]
        BankSpółdzielczywBiałobrzegach,
        [Description("BankSpółdzielczywChynowie")]
        BankSpółdzielczywChynowie,
        [Description("BankSpółdzielczywGłowaczowie")]
        BankSpółdzielczywGłowaczowie,
        [Description("BankSpółdzielczywGrójcu")]
        BankSpółdzielczywGrójcu,
        [Description("BankSpółdzielczywIłży")]
        BankSpółdzielczywIłży,
        [Description("BankSpółdzielczywJasieńcu")]
        BankSpółdzielczywJasieńcu,
        [Description("PołudniowoMazowieckiBankSpółdzielczywJedlińsku")]
        PołudniowoMazowieckiBankSpółdzielczywJedlińsku,
        [Description("BankSpółdzielczywLipsku")]
        BankSpółdzielczywLipsku,
        [Description("BankSpółdzielczywPionkach")]
        BankSpółdzielczywPionkach,
        [Description("BankSpółdzielczywPrzysusze")]
        BankSpółdzielczywPrzysusze,
        [Description("BankSpółdzielczywRadomiu")]
        BankSpółdzielczywRadomiu,
        [Description("BankSpółdzielczywSkaryszewie")]
        BankSpółdzielczywSkaryszewie,
        [Description("BankSpółdzielczywWarce")]
        BankSpółdzielczywWarce,
        [Description("BankSpółdzielczywZwoleniu")]
        BankSpółdzielczywZwoleniu,
        [Description("BankSpółdzielczywBłażowej")]
        BankSpółdzielczywBłażowej,
        [Description("BankSpółdzielczywGłogowieMałopolskim")]
        BankSpółdzielczywGłogowieMałopolskim,
        [Description("BankSpółdzielczywLubeni")]
        BankSpółdzielczywLubeni,
        [Description("BankSpółdzielczywRzeszowie")]
        BankSpółdzielczywRzeszowie,
        [Description("BankSpółdzielczywNiechobrzu")]
        BankSpółdzielczywNiechobrzu,
        [Description("BankSpółdzielczywTyczynie")]
        BankSpółdzielczywTyczynie,
        [Description("BankSpółdzielczywStrzyżowie")]
        BankSpółdzielczywStrzyżowie,
        [Description("BankSpółdzielczywKamieniu")]
        BankSpółdzielczywKamieniu,
        [Description("BankSpółdzielczywRopczycach")]
        BankSpółdzielczywRopczycach,
        [Description("BankSpółdzielczywSędziszowieMłp")]
        BankSpółdzielczywSędziszowieMłp,
        [Description("BankSpółdzielczywWielopoluSkrzyńskim")]
        BankSpółdzielczywWielopoluSkrzyńskim,
        [Description("BankSpółdzielczywŻołyni")]
        BankSpółdzielczywŻołyni,
        [Description("EXPRESSBANKSPÓŁDZIELCZY")]
        EXPRESSBANKSPÓŁDZIELCZY,
        [Description("BankSpółdzielczywŁańcucie")]
        BankSpółdzielczywŁańcucie,
        [Description("BankSpółdzielczywKolbuszowej")]
        BankSpółdzielczywKolbuszowej,
        [Description("BankSpółdzielczywSokołowieMałopolskim")]
        BankSpółdzielczywSokołowieMałopolskim,
        [Description("BankSpółdzielczywMielcu")]
        BankSpółdzielczywMielcu,
        [Description("BankSpółdzielczywPrzecławiu")]
        BankSpółdzielczywPrzecławiu,
        [Description("BankSpółdzielczywLeżajsku")]
        BankSpółdzielczywLeżajsku,
        [Description("BankSpółdzielczywJasionce")]
        BankSpółdzielczywJasionce,
        [Description("BankSpółdzielczywMokobodach")]
        BankSpółdzielczywMokobodach,
        [Description("BankSpółdzielczywSiedlcach")]
        BankSpółdzielczywSiedlcach,
        [Description("BankSpółdzielczywSobieniachJeziorach")]
        BankSpółdzielczywSobieniachJeziorach,
        [Description("MiędzygminnyBankSpółdzielczywZbuczynie")]
        MiędzygminnyBankSpółdzielczywZbuczynie,
        [Description("BankSpółdzielczywAdamowie")]
        BankSpółdzielczywAdamowie,
        [Description("BankSpółdzielczywKrzywdzie")]
        BankSpółdzielczywKrzywdzie,
        [Description("BankSpółdzielczywŁukowie")]
        BankSpółdzielczywŁukowie,
        [Description("BankSpółdzielczywTrzebieszowie")]
        BankSpółdzielczywTrzebieszowie,
        [Description("BankSpółdzielczywGarwolinie")]
        BankSpółdzielczywGarwolinie,
        [Description("BankSpółdzielczywŁaskarzewie")]
        BankSpółdzielczywŁaskarzewie,
        [Description("PowiatowyBankSpółdzielczywSokołowiePodlaskim")]
        PowiatowyBankSpółdzielczywSokołowiePodlaskim,
        [Description("BankSpółdzielczywKałuszynie")]
        BankSpółdzielczywKałuszynie,
        [Description("BankSpółdzielczywMińskuMazowieckim")]
        BankSpółdzielczywMińskuMazowieckim,
        [Description("BankSpółdzielczywMrozach")]
        BankSpółdzielczywMrozach,
        [Description("BankSpółdzielczywŁochowie")]
        BankSpółdzielczywŁochowie,
        [Description("PowiatowyBankSpółdzielczywWęgrowie")]
        PowiatowyBankSpółdzielczywWęgrowie,
        [Description("BankSpółdzielczyZiemiWieluńskiej")]
        BankSpółdzielczyZiemiWieluńskiej,
        [Description("BankSpółdzielczywBłaszkach")]
        BankSpółdzielczywBłaszkach,
        [Description("NadwarciańskiBankSpółdzielczywDziałoszynie")]
        NadwarciańskiBankSpółdzielczywDziałoszynie,
        [Description("RejonowyBankSpółdzielczywLututowie")]
        RejonowyBankSpółdzielczywLututowie,
        [Description("BankSpółdzielczywPoddębicach")]
        BankSpółdzielczywPoddębicach,
        [Description("BankSpółdzielczywRuścu")]
        BankSpółdzielczywRuścu,
        [Description("BankSpółdzielczywSieradzu")]
        BankSpółdzielczywSieradzu,
        [Description("BankSpółdzielczywSzadku")]
        BankSpółdzielczywSzadku,
        [Description("BankSpółdzielczywWarcie")]
        BankSpółdzielczywWarcie,
        [Description("BankSpółdzielczywWartkowicach")]
        BankSpółdzielczywWartkowicach,
        [Description("LudowyBankSpółdzielczywZduńskiejWoli")]
        LudowyBankSpółdzielczywZduńskiejWoli,
        [Description("BankSpółdzielczywSochaczewie")]
        BankSpółdzielczywSochaczewie,
        [Description("BankSpółdzielczywTeresinie")]
        BankSpółdzielczywTeresinie,
        [Description("BankSpółdzielczyZiemiŁowickiejwŁowiczu")]
        BankSpółdzielczyZiemiŁowickiejwŁowiczu,
        [Description("BankSpółdzielczywBiałejRawskiej")]
        BankSpółdzielczywBiałejRawskiej,
        [Description("BankSpółdzielczywSkierniewicach")]
        BankSpółdzielczywSkierniewicach,
        [Description("BankSpółdzielczywMszczonowie")]
        BankSpółdzielczywMszczonowie,
        [Description("BankSpółdzielczywWiskitkach")]
        BankSpółdzielczywWiskitkach,
        [Description("BankSpółdzielczywUstce")]
        BankSpółdzielczywUstce,
        [Description("BankSpółdzielczywSławnie")]
        BankSpółdzielczywSławnie,
        [Description("BankSpółdzielczywBytowie")]
        BankSpółdzielczywBytowie,
        [Description("BankSpółdzielczywebie")]
        BankSpółdzielczywebie,
        [Description("BankSpółdzielczywCzłuchowie")]
        BankSpółdzielczywCzłuchowie,
        [Description("BankSpółdzielczywEłku")]
        BankSpółdzielczywEłku,
        [Description("BankSpółdzielczywBargłowieKościelnym")]
        BankSpółdzielczywBargłowieKościelnym,
        [Description("BankSpółdzielczywOlecku")]
        BankSpółdzielczywOlecku,
        [Description("MazurskiBankSpółdzielczywGiżycku")]
        MazurskiBankSpółdzielczywGiżycku,
        [Description("BankSpółdzielczywWęgorzewie")]
        BankSpółdzielczywWęgorzewie,
        [Description("BankSpółdzielczywMikołajkach")]
        BankSpółdzielczywMikołajkach,
        [Description("BankSpółdzielczywAugustowie")]
        BankSpółdzielczywAugustowie,
        [Description("BankSpółdzielczywSejnach")]
        BankSpółdzielczywSejnach,
        [Description("BankSpółdzielczywSuwałkach")]
        BankSpółdzielczywSuwałkach,
        [Description("WarmińskoMazurskiBankSpółdzielczy")]
        WarmińskoMazurskiBankSpółdzielczy,
        [Description("BankSpółdzielczywRutceTartak")]
        BankSpółdzielczywRutceTartak,
        [Description("BankSpółdzielczywChojnie")]
        BankSpółdzielczywChojnie,
        [Description("BankSpółdzielczywGoleniowie")]
        BankSpółdzielczywGoleniowie,
        [Description("BankSpółdzielczywGryficach")]
        BankSpółdzielczywGryficach,
        [Description("BankSpółdzielczywGryfinie")]
        BankSpółdzielczywGryfinie,
        [Description("BankSpółdzielczywMiędzyzdrojach")]
        BankSpółdzielczywMiędzyzdrojach,
        [Description("PyrzyckoStargardzkiBankSpółdzielczy")]
        PyrzyckoStargardzkiBankSpółdzielczy,
        [Description("BankSpółdzielczywWolinie")]
        BankSpółdzielczywWolinie,
        [Description("PowiatowyBankSpółdzielczywPolicach")]
        PowiatowyBankSpółdzielczywPolicach,
        [Description("BankSpółdzielczyRzemiosławSzczecinie")]
        BankSpółdzielczyRzemiosławSzczecinie,
        [Description("BankSpółdzielczywGrębowie")]
        BankSpółdzielczywGrębowie,
        [Description("PowiatowyBankSpółdzielczywJanowieLubelskim")]
        PowiatowyBankSpółdzielczywJanowieLubelskim,
        [Description("BankSpółdzielczywOżarowie")]
        BankSpółdzielczywOżarowie,
        [Description("BankSpółdzielczywPołańcu")]
        BankSpółdzielczywPołańcu,
        [Description("BankSpółdzielczywSandomierzu")]
        BankSpółdzielczywSandomierzu,
        [Description("NadsańskiBankSpółdzielczy")]
        NadsańskiBankSpółdzielczy,
        [Description("BankSpółdzielczywStaszowie")]
        BankSpółdzielczywStaszowie,
        [Description("BankSpółdzielczywTarnobrzegu")]
        BankSpółdzielczywTarnobrzegu,
        [Description("BankSpółdzielczywZaleszanach")]
        BankSpółdzielczywZaleszanach,
        [Description("BankSpółdzielczywBrzesku")]
        BankSpółdzielczywBrzesku,
        [Description("BankSpółdzielczywDąbrowieTarnowskiej")]
        BankSpółdzielczywDąbrowieTarnowskiej,
        [Description("BankSpółdzielczywSzczucinie")]
        BankSpółdzielczywSzczucinie,
        [Description("BankSpółdzielczywDębicy")]
        BankSpółdzielczywDębicy,
        [Description("BankSpółdzielczywPilźnie")]
        BankSpółdzielczywPilźnie,
        [Description("BankSpółdzielczywŻyrakowie")]
        BankSpółdzielczywŻyrakowie,
        [Description("BankSpółdzielczywRadomyśluWielkim")]
        BankSpółdzielczywRadomyśluWielkim,
        [Description("BankSpółdzielczywBrodnicy")]
        BankSpółdzielczywBrodnicy,
        [Description("BankSpółdzielczywChełmnie")]
        BankSpółdzielczywChełmnie,
        [Description("BankSpółdzielczywGolubiuDobrzyniu")]
        BankSpółdzielczywGolubiuDobrzyniu,
        [Description("BankSpółdzielczywGrębocinie")]
        BankSpółdzielczywGrębocinie,
        [Description("BankSpółdzielczywKowalewiePomorskim")]
        BankSpółdzielczywKowalewiePomorskim,
        [Description("BankSpółdzielczywŁasinie")]
        BankSpółdzielczywŁasinie,
        [Description("BankSpółdzielczywToruniu")]
        BankSpółdzielczywToruniu,
        [Description("BankSpółdzielczywKłodzku")]
        BankSpółdzielczywKłodzku,
        [Description("BankSpółdzielczywDzierżoniowie")]
        BankSpółdzielczywDzierżoniowie,
        [Description("BankSpółdzielczywŚwidnicy")]
        BankSpółdzielczywŚwidnicy,
        [Description("BankSpółdzielczywZąbkowicachŚląskich")]
        BankSpółdzielczywZąbkowicachŚląskich,
        [Description("GospodarczyBankSpółdzielczyRadkówzswNowejRudzie")]
        GospodarczyBankSpółdzielczyRadkówzswNowejRudzie,
        [Description("KujawskiBankSpółdzielczywAleksandrowieKujawskim")]
        KujawskiBankSpółdzielczywAleksandrowieKujawskim,
        [Description("BankSpółdzielczywLipnie")]
        BankSpółdzielczywLipnie,
        [Description("BankSpółdzielczywSkępem")]
        BankSpółdzielczywSkępem,
        [Description("BankSpółdzielczywRadziejowie")]
        BankSpółdzielczywRadziejowie,
        [Description("KujawskoDobrzyńskiBankSpółdzielczy")]
        KujawskoDobrzyńskiBankSpółdzielczy,
        [Description("BankSpółdzielczywPiotrkowieKujawskim")]
        BankSpółdzielczywPiotrkowieKujawskim,
        [Description("BankSpółdzielczywKowalu")]
        BankSpółdzielczywKowalu,
        [Description("BankSpółdzielczywLubrańcu")]
        BankSpółdzielczywLubrańcu,
        [Description("BankSpółdzielczywKątachWrocławskich")]
        BankSpółdzielczywKątachWrocławskich,
        [Description("BankSpółdzielczywKobierzycach")]
        BankSpółdzielczywKobierzycach,
        [Description("BankSpółdzielczywMiliczu")]
        BankSpółdzielczywMiliczu,
        [Description("BankSpółdzielczywObornikachŚląskich")]
        BankSpółdzielczywObornikachŚląskich,
        [Description("BankSpółdzielczywOleśnicy")]
        BankSpółdzielczywOleśnicy,
        [Description("BankSpółdzielczywOławie")]
        BankSpółdzielczywOławie,
        [Description("PowiatowyBankSpółdzielczywStrzelinie")]
        PowiatowyBankSpółdzielczywStrzelinie,
        [Description("BankSpółdzielczywŚrodzieŚląskiej")]
        BankSpółdzielczywŚrodzieŚląskiej,
        [Description("BankSpółdzielczywTrzebnicy")]
        BankSpółdzielczywTrzebnicy,
        [Description("BankSpółdzielczywŻmigrodzie")]
        BankSpółdzielczywŻmigrodzie,
        [Description("BankSpółdzielczywBiłgoraju")]
        BankSpółdzielczywBiłgoraju,
        [Description("BankSpółdzielczywDołhobyczowie")]
        BankSpółdzielczywDołhobyczowie,
        [Description("BankSpółdzielczyweFrampolu")]
        BankSpółdzielczyweFrampolu,
        [Description("BankSpółdzielczywIzbicy")]
        BankSpółdzielczywIzbicy,
        [Description("BankSpółdzielczywKsiężpolu")]
        BankSpółdzielczywKsiężpolu,
        [Description("BankSpółdzielczywLubyczyKrólewskiej")]
        BankSpółdzielczywLubyczyKrólewskiej,
        [Description("BankSpółdzielczywŁukowej")]
        BankSpółdzielczywŁukowej,
        [Description("BankSpółdzielczywŁaszczowie")]
        BankSpółdzielczywŁaszczowie,
        [Description("BankSpółdzielczywObszy")]
        BankSpółdzielczywObszy,
        [Description("BankSpółdzielczywNieliszuzswStawieNoakowskim")]
        BankSpółdzielczywNieliszuzswStawieNoakowskim,
        [Description("BankSpółdzielczywSzczebrzeszynie")]
        BankSpółdzielczywSzczebrzeszynie,
        [Description("BankSpółdzielczywTarnogrodzie")]
        BankSpółdzielczywTarnogrodzie,
        [Description("BankSpółdzielczywTomaszowieLubelskim")]
        BankSpółdzielczywTomaszowieLubelskim,
        [Description("BankSpółdzielczywWerbkowicach")]
        BankSpółdzielczywWerbkowicach,
        [Description("PowiatowyBankSpółdzielczywZamościu")]
        PowiatowyBankSpółdzielczywZamościu,
        [Description("BankSpółdzielczywBiszczy")]
        BankSpółdzielczywBiszczy,
        [Description("BankSpółdzielczywKrośnieOdrzańskim")]
        BankSpółdzielczywKrośnieOdrzańskim,
        [Description("BankSpółdzielczywŻaganiu")]
        BankSpółdzielczywŻaganiu,
        [Description("BankSpółdzielczywIłowej")]
        BankSpółdzielczywIłowej,
        [Description("BankSpółdzielczywSiedlcu")]
        BankSpółdzielczywSiedlcu,
        [Description("BankSpółdzielczywTrzebielu")]
        BankSpółdzielczywTrzebielu,
        [Description("BankSpółdzielczywKożuchowie")]
        BankSpółdzielczywKożuchowie,
        [Description("BankSpółdzielczywNowejSoli")]
        BankSpółdzielczywNowejSoli,
        [Description("BankSpółdzielczywGrodziskuMazowieckim")]
        BankSpółdzielczywGrodziskuMazowieckim,
        [Description("PowiatowyBankSpółdzielczyweWrześni")]
        PowiatowyBankSpółdzielczyweWrześni,
    }
}
