using System.ComponentModel;
namespace Wonga.QA.Framework.Api.Enums
{
    public enum CityOfUniversityEnum
    {
        [Description("Warszawa")]
        Warszawa,
        [Description("Białystok")]
        Białystok,
        [Description("Gdańsk")]
        Gdańsk,
        [Description("Poznań")]
        Poznań,
        [Description("Kraków")]
        Kraków,
        [Description("Łódż")]
        Łódż,
        [Description("Lublin")]
        Lublin,
        [Description("Lubin")]
        Lubin,
        [Description("Toruń")]
        Toruń,
        [Description("Opole")]
        Opole,
        [Description("Szczecin")]
        Szczecin,
        [Description("Katowice")]
        Katowice,
        [Description("Rzeszów")]
        Rzeszów,
        [Description("Olsztyn")]
        Olsztyn,
        [Description("Wrocław")]
        Wrocław,
        [Description("ZielonaGóra")]
        ZielonaGóra,
        [Description("Bydgoszcz")]
        Bydgoszcz,
        [Description("Kielce")]
        Kielce,
        [Description("BielskoBiała")]
        BielskoBiała,
        [Description("Częstochowa")]
        Częstochowa,
        [Description("Gliwice")]
        Gliwice,
        [Description("Koszalin")]
        Koszalin,
        [Description("Radom")]
        Radom,
        [Description("Słupsk")]
        Słupsk,
        [Description("Siedlce")]
        Siedlce,
        [Description("Elbląg")]
        Elbląg,
        [Description("GorzówWielkopolski")]
        GorzówWielkopolski,
        [Description("JeleniaGóra")]
        JeleniaGóra,
        [Description("Konin")]
        Konin,
        [Description("Legnica")]
        Legnica,
        [Description("NowySącz")]
        NowySącz,
        [Description("Jarosław")]
        Jarosław,
        [Description("Sulechów")]
        Sulechów,
        [Description("Leszno")]
        Leszno,
        [Description("Krosno")]
        Krosno,
        [Description("Kalisz")]
        Kalisz,
        [Description("Piła")]
        Piła,
        [Description("BiałaPodlaska")]
        BiałaPodlaska,
        [Description("Przemyśl")]
        Przemyśl,
        [Description("Tarnobrzeg")]
        Tarnobrzeg,
        [Description("Nysa")]
        Nysa,
        [Description("Chełm")]
        Chełm,
        [Description("NowyTarg")]
        NowyTarg,
        [Description("Ciechanów")]
        Ciechanów,
        [Description("Włocławek")]
        Włocławek,
        [Description("Racibórz")]
        Racibórz,
        [Description("Łomża")]
        Łomża,
        [Description("Głogów")]
        Głogów,
        [Description("Gniezno")]
        Gniezno,
        [Description("Wałcz")]
        Wałcz,
        [Description("Oświęcim")]
        Oświęcim,
        [Description("Zamość")]
        Zamość,
        [Description("Suwałki")]
        Suwałki,
        [Description("Skierniewice")]
        Skierniewice,
        [Description("Sandomierz")]
        Sandomierz,
        [Description("Bochnia")]
        Bochnia,
        [Description("Brzeg")]
        Brzeg,
        [Description("Brzesko")]
        Brzesko,
        [Description("Bytom")]
        Bytom,
        [Description("Chojnice")]
        Chojnice,
        [Description("Chorzów")]
        Chorzów,
        [Description("Chrzanów")]
        Chrzanów,
        [Description("Dąbrowagórnicza")]
        Dąbrowagórnicza,
        [Description("Ełk")]
        Ełk,
        [Description("Falenty")]
        Falenty,
        [Description("Gdynia")]
        Gdynia,
        [Description("Giżycko")]
        Giżycko,
        [Description("Grudziądz")]
        Grudziądz,
        [Description("Jarocin")]
        Jarocin,
        [Description("Jasło")]
        Jasło,
        [Description("Józefów")]
        Józefów,
        [Description("Junoszyno")]
        Junoszyno,
        [Description("Kostrzyńnadodrą")]
        Kostrzyńnadodrą,
        [Description("Kęty")]
        Kęty,
        [Description("Kutno")]
        Kutno,
        [Description("Kwidzyn")]
        Kwidzyn,
        [Description("Lublin1")]
        Lublin1,
        [Description("Łomianki")]
        Łomianki,
        [Description("Łowicz")]
        Łowicz,
        [Description("Łódź")]
        Łódź,
        [Description("Łuków")]
        Łuków,
        [Description("Nowaruda")]
        Nowaruda,
        [Description("Olecko")]
        Olecko,
        [Description("Ostrołęka")]
        Ostrołęka,
        [Description("Ostrowiecświętokrzyski")]
        Ostrowiecświętokrzyski,
        [Description("Mysłowice")]
        Mysłowice,
        [Description("Nadarzyn")]
        Nadarzyn,
        [Description("NowySącz1")]
        NowySącz1,
        [Description("Sochaczew")]
        Sochaczew,
        [Description("Sopot")]
        Sopot,
        [Description("Sosnowiec")]
        Sosnowiec,
        [Description("StalowaWola")]
        StalowaWola,
        [Description("Inne")]
        Inne,
    }
}
