using System.ComponentModel;
namespace Wonga.QA.Framework.Api.Enums
{
    public enum EmploymentIndustryPlEnum
    {
        [Description("Rolnictwo")]
        Rolnictwo,
        [Description("Leśnictwo")]
        Leśnictwo,
        [Description("Łowiectwoirybołówstwo")]
        Łowiectwoirybołówstwo,
        [Description("Górnictwoiprzemysłwydobywczy")]
        Górnictwoiprzemysłwydobywczy,
        [Description("Przemysłprzetworczy")]
        Przemysłprzetworczy,
        [Description("Administracjapaństwowa")]
        Administracjapaństwowa,
        [Description("Uslugikomunalne")]
        Uslugikomunalne,
        [Description("Przemysłenergetyczny")]
        Przemysłenergetyczny,
        [Description("Budownictwo")]
        Budownictwo,
        [Description("Handelhurtowyidetaliczny")]
        Handelhurtowyidetaliczny,
        [Description("Uslugi")]
        Uslugi,
        [Description("Transportilogistyka")]
        Transportilogistyka,
        [Description("Turystyka")]
        Turystyka,
        [Description("Telekomunikacja")]
        Telekomunikacja,
        [Description("Media")]
        Media,
        [Description("Finanseiubezpieczenia")]
        Finanseiubezpieczenia,
        [Description("Nieruchomości")]
        Nieruchomości,
        [Description("Edukacja")]
        Edukacja,
        [Description("Opiekazdrowotna")]
        Opiekazdrowotna,
        [Description("Kulturairozrywka")]
        Kulturairozrywka,
        [Description("Inna")]
        Inna,
    }
}
