using System.ComponentModel;
namespace Wonga.QA.Framework.Api.Enums
{
    public enum EmploymentIndustryEnum
    {
        [Description("Accountancy")]
        Accountancy,
        [Description("Advertising")]
        Advertising,
        [Description("BusinessConsultancy")]
        BusinessConsultancy,
        [Description("CallCentreOperations")]
        CallCentreOperations,
        [Description("Cleaning")]
        Cleaning,
        [Description("ComputerServices")]
        ComputerServices,
        [Description("Construction")]
        Construction,
        [Description("Education")]
        Education,
        [Description("Electricity")]
        Electricity,
        [Description("Finance")]
        Finance,
        [Description("Health")]
        Health,
        [Description("HotelsRestaurants")]
        HotelsRestaurants,
        [Description("Insurance")]
        Insurance,
        [Description("LegalServices")]
        LegalServices,
        [Description("LeisureCulture")]
        LeisureCulture,
        [Description("Manufacturing")]
        Manufacturing,
        [Description("Mining")]
        Mining,
        [Description("PublicAdministration")]
        PublicAdministration,
        [Description("Publishing")]
        Publishing,
        [Description("Property")]
        Property,
        [Description("ResearchDevelopment")]
        ResearchDevelopment,
        [Description("Retail")]
        Retail,
        [Description("TelecomsInternet")]
        TelecomsInternet,
        [Description("Transportation")]
        Transportation,
    }
}
