using System.ComponentModel;
namespace Wonga.QA.Framework.Api
{
    public enum EmploymentPositionEnum
    {
        [Description("Actor")]
        Actor,
        [Description("Administration")]
        Administration,
        [Description("BusDriver")]
        BusDriver,
        [Description("BusinessDevelopment")]
        BusinessDevelopment,
        [Description("BusinessOwner")]
        BusinessOwner,
        [Description("Consultancy")]
        Consultancy,
        [Description("Doctor")]
        Doctor,
        [Description("Engineering")]
        Engineering,
        [Description("Firefighter")]
        Firefighter,
        [Description("Management")]
        Management,
        [Description("Marketing")]
        Marketing,
        [Description("CabDriver")]
        CabDriver,
        [Description("Musician")]
        Musician,
        [Description("Nurse")]
        Nurse,
        [Description("Other")]
        Other,
        [Description("Sales")]
        Sales,
        [Description("SeniorManagerDirector")]
        SeniorManagerDirector,
        [Description("Services")]
        Services,
        [Description("Teacher")]
        Teacher,
        [Description("TruckDriver")]
        TruckDriver,
        [Description("TaxiDriver")]
        TaxiDriver,
    }
}
