namespace Wonga.QA.Framework.Api
{
    public enum EmploymentIndustryEnum
    {
        Accountancy,
        Advertising,
        BusinessConsultancy,
        CallCentreOperations,
        Cleaning,
        ComputerServices,
        Construction,
        Education,
        Electricity,
        Finance,
        Health,
        HotelsRestaurants,
        Insurance,
        LegalServices,
        LeisureCulture,
        Manufacturing,
        Mining,
        PublicAdministration,
        Publishing,
        Property,
        ResearchDevelopment,
        Retail,
        TelecomsInternet,
        Transportation,
    }
}
