using System.ComponentModel;
namespace Wonga.QA.Framework.Api.Enums
{
    public enum EmploymentPositionCaEnum
    {
        [Description("EmergencyServices")]
        EmergencyServices,
        [Description("Government")]
        Government,
        [Description("Healthcare")]
        Healthcare,
        [Description("Management")]
        Management,
        [Description("Manufacturing")]
        Manufacturing,
        [Description("MiningAgriculture")]
        MiningAgriculture,
        [Description("Professional")]
        Professional,
        [Description("RestaurantFoodServices")]
        RestaurantFoodServices,
        [Description("Retail")]
        Retail,
        [Description("Other")]
        Other,
        [Description("Sales")]
        Sales,
        [Description("Retail1")]
        Retail1,
        [Description("Services")]
        Services,
        [Description("Teacher")]
        Teacher,
        [Description("Technical")]
        Technical,
        [Description("Trades")]
        Trades,
    }
}
