//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wonga.QA.Tests.Risk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wonga.QA.Tests.Risk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steven,lee,hilton,1977-09-29,5,CF33 6JG,Ffordd Ddu,Bridgend;Kerry,ann,Tumilty,1981-03-02,14,NE28 9DS,bellingham close,wallsend;gareth,damon,horvath,1992-05-25,27,M33 5NQ,Witley Drive,Sale;Neil,Anthony,Ashmore,1987-10-23,28,NG11 8RQ,Wilkins Gardens,Nottingham;charlotte,l,omalley,1978-01-02,40,PO13 9JY,Bayntun Drive,Lee-on-the-Solent;paula,a,mitchell,1978-09-07,543,DD2 4FP,South Road,Dundee;emma,jane,potgieter,1981-07-06,54,BN13 2SZ,Vancouver Road,Worthing;victoria,sheila joan,lawrence,1988-08-10,47,NR31 6SQ, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomerDataforCallCredit {
            get {
                return ResourceManager.GetString("CustomerDataforCallCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to samantha,jane,gettings,29669,8,M18 8AH,Bealey Close,Manchester,8447444;Christopher,James,Hatfield,33935,12,TS23 3XJ,Wallington Walk,Billingham,8447116;linda,christine,greer,31380,13,G84 7LH,Williamson Drive,Helensburgh,8447107;rebekah louise,NULL,lewis,33270,6,B67 6JF,Valley Road,Smethwick,8446990;Kevin,NULL,Wardman,31744,21,BD5 7PA,Lindley Road,Bradford,8446926;DONNA,LOUISE,LAMBERT,29020,107,YO24 4PS,Green Lane,York,8446889;shahmus,NULL,hussain,31877,85,WF13 3NJ,Pilgrim Crescent,Dewsbury,8446843;Joanne,NUL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZScoreCustomers {
            get {
                return ResourceManager.GetString("ZScoreCustomers", resourceCulture);
            }
        }
    }
}
