using System.ComponentModel;
namespace Wonga.QA.Framework.Cs.Enums
{
    public enum PaymentTransactionEnum
    {
        [Description("CashAdvance")]
        CashAdvance,
        [Description("Fee")]
        Fee,
        [Description("LoanExtensionFee")]
        LoanExtensionFee,
        [Description("Interest")]
        Interest,
        [Description("DefaultCharge")]
        DefaultCharge,
        [Description("CardPayment")]
        CardPayment,
        [Description("DirectBankPayment")]
        DirectBankPayment,
        [Description("SuspendInterestAccrual")]
        SuspendInterestAccrual,
        [Description("ResumeInterestAccrual")]
        ResumeInterestAccrual,
        [Description("WriteOff")]
        WriteOff,
        [Description("DebtSale")]
        DebtSale,
        [Description("DebtSaleProceeds")]
        DebtSaleProceeds,
        [Description("InterestWriteOff")]
        InterestWriteOff,
        [Description("AgencyFee")]
        AgencyFee,
        [Description("Adjustment")]
        Adjustment,
        [Description("ArrearsLetterCharge")]
        ArrearsLetterCharge,
        [Description("OutsourcedAgencyPayment")]
        OutsourcedAgencyPayment,
        [Description("Refund")]
        Refund,
        [Description("Chargeback")]
        Chargeback,
        [Description("Cheque")]
        Cheque,
        [Description("V2MigratedInsurance")]
        V2MigratedInsurance,
        [Description("V2MigratedWriteOff")]
        V2MigratedWriteOff,
        [Description("V2MigratedCharge")]
        V2MigratedCharge,
        [Description("V2MigratedPayment")]
        V2MigratedPayment,
        [Description("V2Migratedadvance")]
        V2Migratedadvance,
        [Description("ServiceFee")]
        ServiceFee,
        [Description("InitiationFee")]
        InitiationFee,
        [Description("InterestRate")]
        InterestRate,
        [Description("InterestRateFee")]
        InterestRateFee,
        [Description("InterestAdjustment")]
        InterestAdjustment,
        [Description("RegularCardPayment")]
        RegularCardPayment,
        [Description("Dispute")]
        Dispute,
        [Description("DirectDeposit")]
        DirectDeposit,
        [Description("InterestReversal")]
        InterestReversal,
        [Description("ServiceFeeWriteOff")]
        ServiceFeeWriteOff,
        [Description("ServiceFeeReversal")]
        ServiceFeeReversal,
        [Description("InitiationFeeWriteOff")]
        InitiationFeeWriteOff,
        [Description("InitiationFeeReversal")]
        InitiationFeeReversal,
    }
}
