#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wonga.QA.Framework.Db.QAData
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QAData")]
	public partial class QaDataDatabase : DbDatabase<QaDataDatabase>
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCallReportResponse(CallReportResponse instance);
    partial void UpdateCallReportResponse(CallReportResponse instance);
    partial void DeleteCallReportResponse(CallReportResponse instance);
    partial void InsertCallValidateOutput(CallValidateOutput instance);
    partial void UpdateCallValidateOutput(CallValidateOutput instance);
    partial void DeleteCallValidateOutput(CallValidateOutput instance);
    partial void InsertExperianBWCardResponse(ExperianBWCardResponse instance);
    partial void UpdateExperianBWCardResponse(ExperianBWCardResponse instance);
    partial void DeleteExperianBWCardResponse(ExperianBWCardResponse instance);
    partial void InsertExperianBWVerifyResponse(ExperianBWVerifyResponse instance);
    partial void UpdateExperianBWVerifyResponse(ExperianBWVerifyResponse instance);
    partial void DeleteExperianBWVerifyResponse(ExperianBWVerifyResponse instance);
    partial void InsertExperianResponse(ExperianResponse instance);
    partial void UpdateExperianResponse(ExperianResponse instance);
    partial void DeleteExperianResponse(ExperianResponse instance);
    partial void InsertGraydonCompanyReport(GraydonCompanyReport instance);
    partial void UpdateGraydonCompanyReport(GraydonCompanyReport instance);
    partial void DeleteGraydonCompanyReport(GraydonCompanyReport instance);
    partial void InsertIncomingBankGatewayScotiaFile(IncomingBankGatewayScotiaFile instance);
    partial void UpdateIncomingBankGatewayScotiaFile(IncomingBankGatewayScotiaFile instance);
    partial void DeleteIncomingBankGatewayScotiaFile(IncomingBankGatewayScotiaFile instance);
    partial void InsertIovationDataOutput(IovationDataOutput instance);
    partial void UpdateIovationDataOutput(IovationDataOutput instance);
    partial void DeleteIovationDataOutput(IovationDataOutput instance);
    partial void InsertMSSQLDeploy(MSSQLDeploy instance);
    partial void UpdateMSSQLDeploy(MSSQLDeploy instance);
    partial void DeleteMSSQLDeploy(MSSQLDeploy instance);
    #endregion
		
		public QaDataDatabase(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QaDataDatabase(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QaDataDatabase(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QaDataDatabase(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CallReportResponse> CallReportResponses
		{
			get
			{
				return this.GetTable<CallReportResponse>();
			}
		}
		
		public System.Data.Linq.Table<CallValidateOutput> CallValidateOutputs
		{
			get
			{
				return this.GetTable<CallValidateOutput>();
			}
		}
		
		public System.Data.Linq.Table<ExperianBWCardResponse> ExperianBWCardResponses
		{
			get
			{
				return this.GetTable<ExperianBWCardResponse>();
			}
		}
		
		public System.Data.Linq.Table<ExperianBWVerifyResponse> ExperianBWVerifyResponses
		{
			get
			{
				return this.GetTable<ExperianBWVerifyResponse>();
			}
		}
		
		public System.Data.Linq.Table<ExperianResponse> ExperianResponses
		{
			get
			{
				return this.GetTable<ExperianResponse>();
			}
		}
		
		public System.Data.Linq.Table<GraydonCompanyReport> GraydonCompanyReports
		{
			get
			{
				return this.GetTable<GraydonCompanyReport>();
			}
		}
		
		public System.Data.Linq.Table<IncomingBankGatewayScotiaFile> IncomingBankGatewayScotiaFiles
		{
			get
			{
				return this.GetTable<IncomingBankGatewayScotiaFile>();
			}
		}
		
		public System.Data.Linq.Table<IovationDataOutput> IovationDataOutputs
		{
			get
			{
				return this.GetTable<IovationDataOutput>();
			}
		}
		
		public System.Data.Linq.Table<MSSQLDeploy> MSSQLDeploys
		{
			get
			{
				return this.GetTable<MSSQLDeploy>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CallReportResponse")]
	public partial class CallReportResponse : DbEntity<CallReportResponse>, INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CallReportResponseId;
		
		private int _WaitTimeInSeconds;
		
		private string _Forename;
		
		private string _Surname;
		
		private string _Response;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCallReportResponseIdChanging(int value);
    partial void OnCallReportResponseIdChanged();
    partial void OnWaitTimeInSecondsChanging(int value);
    partial void OnWaitTimeInSecondsChanged();
    partial void OnForenameChanging(string value);
    partial void OnForenameChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnResponseChanging(string value);
    partial void OnResponseChanged();
    #endregion
		
		public CallReportResponse()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallReportResponseId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CallReportResponseId
		{
			get
			{
				return this._CallReportResponseId;
			}
			set
			{
				if ((this._CallReportResponseId != value))
				{
					this.OnCallReportResponseIdChanging(value);
					this.SendPropertyChanging();
					this._CallReportResponseId = value;
					this.SendPropertyChanged("CallReportResponseId");
					this.OnCallReportResponseIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaitTimeInSeconds", DbType="Int NOT NULL")]
		public int WaitTimeInSeconds
		{
			get
			{
				return this._WaitTimeInSeconds;
			}
			set
			{
				if ((this._WaitTimeInSeconds != value))
				{
					this.OnWaitTimeInSecondsChanging(value);
					this.SendPropertyChanging();
					this._WaitTimeInSeconds = value;
					this.SendPropertyChanged("WaitTimeInSeconds");
					this.OnWaitTimeInSecondsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Forename", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Forename
		{
			get
			{
				return this._Forename;
			}
			set
			{
				if ((this._Forename != value))
				{
					this.OnForenameChanging(value);
					this.SendPropertyChanging();
					this._Forename = value;
					this.SendPropertyChanged("Forename");
					this.OnForenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Response", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Response
		{
			get
			{
				return this._Response;
			}
			set
			{
				if ((this._Response != value))
				{
					this.OnResponseChanging(value);
					this.SendPropertyChanging();
					this._Response = value;
					this.SendPropertyChanged("Response");
					this.OnResponseChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CallValidateOutput")]
	public partial class CallValidateOutput : DbEntity<CallValidateOutput>, INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CallValidateOutputId;
		
		private int _WaitTimeInSeconds;
		
		private string _ResponseType;
		
		private string _Response;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCallValidateOutputIdChanging(int value);
    partial void OnCallValidateOutputIdChanged();
    partial void OnWaitTimeInSecondsChanging(int value);
    partial void OnWaitTimeInSecondsChanged();
    partial void OnResponseTypeChanging(string value);
    partial void OnResponseTypeChanged();
    partial void OnResponseChanging(string value);
    partial void OnResponseChanged();
    #endregion
		
		public CallValidateOutput()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallValidateOutputId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CallValidateOutputId
		{
			get
			{
				return this._CallValidateOutputId;
			}
			set
			{
				if ((this._CallValidateOutputId != value))
				{
					this.OnCallValidateOutputIdChanging(value);
					this.SendPropertyChanging();
					this._CallValidateOutputId = value;
					this.SendPropertyChanged("CallValidateOutputId");
					this.OnCallValidateOutputIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaitTimeInSeconds", DbType="Int NOT NULL")]
		public int WaitTimeInSeconds
		{
			get
			{
				return this._WaitTimeInSeconds;
			}
			set
			{
				if ((this._WaitTimeInSeconds != value))
				{
					this.OnWaitTimeInSecondsChanging(value);
					this.SendPropertyChanging();
					this._WaitTimeInSeconds = value;
					this.SendPropertyChanged("WaitTimeInSeconds");
					this.OnWaitTimeInSecondsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResponseType", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ResponseType
		{
			get
			{
				return this._ResponseType;
			}
			set
			{
				if ((this._ResponseType != value))
				{
					this.OnResponseTypeChanging(value);
					this.SendPropertyChanging();
					this._ResponseType = value;
					this.SendPropertyChanged("ResponseType");
					this.OnResponseTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Response", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Response
		{
			get
			{
				return this._Response;
			}
			set
			{
				if ((this._Response != value))
				{
					this.OnResponseChanging(value);
					this.SendPropertyChanging();
					this._Response = value;
					this.SendPropertyChanged("Response");
					this.OnResponseChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExperianBWCardResponse")]
	public partial class ExperianBWCardResponse : DbEntity<ExperianBWCardResponse>, INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ExperianBWCardResponseId;
		
		private int _WaitTimeInSeconds;
		
		private string _CVV;
		
		private string _Response;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExperianBWCardResponseIdChanging(int value);
    partial void OnExperianBWCardResponseIdChanged();
    partial void OnWaitTimeInSecondsChanging(int value);
    partial void OnWaitTimeInSecondsChanged();
    partial void OnCVVChanging(string value);
    partial void OnCVVChanged();
    partial void OnResponseChanging(string value);
    partial void OnResponseChanged();
    #endregion
		
		public ExperianBWCardResponse()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExperianBWCardResponseId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ExperianBWCardResponseId
		{
			get
			{
				return this._ExperianBWCardResponseId;
			}
			set
			{
				if ((this._ExperianBWCardResponseId != value))
				{
					this.OnExperianBWCardResponseIdChanging(value);
					this.SendPropertyChanging();
					this._ExperianBWCardResponseId = value;
					this.SendPropertyChanged("ExperianBWCardResponseId");
					this.OnExperianBWCardResponseIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaitTimeInSeconds", DbType="Int NOT NULL")]
		public int WaitTimeInSeconds
		{
			get
			{
				return this._WaitTimeInSeconds;
			}
			set
			{
				if ((this._WaitTimeInSeconds != value))
				{
					this.OnWaitTimeInSecondsChanging(value);
					this.SendPropertyChanging();
					this._WaitTimeInSeconds = value;
					this.SendPropertyChanged("WaitTimeInSeconds");
					this.OnWaitTimeInSecondsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVV", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CVV
		{
			get
			{
				return this._CVV;
			}
			set
			{
				if ((this._CVV != value))
				{
					this.OnCVVChanging(value);
					this.SendPropertyChanging();
					this._CVV = value;
					this.SendPropertyChanged("CVV");
					this.OnCVVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Response", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Response
		{
			get
			{
				return this._Response;
			}
			set
			{
				if ((this._Response != value))
				{
					this.OnResponseChanging(value);
					this.SendPropertyChanging();
					this._Response = value;
					this.SendPropertyChanged("Response");
					this.OnResponseChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExperianBWVerifyResponse")]
	public partial class ExperianBWVerifyResponse : DbEntity<ExperianBWVerifyResponse>, INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ExperianBWVerifyResponseId;
		
		private int _WaitTimeInSeconds;
		
		private string _AccountNumber;
		
		private string _Response;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExperianBWVerifyResponseIdChanging(int value);
    partial void OnExperianBWVerifyResponseIdChanged();
    partial void OnWaitTimeInSecondsChanging(int value);
    partial void OnWaitTimeInSecondsChanged();
    partial void OnAccountNumberChanging(string value);
    partial void OnAccountNumberChanged();
    partial void OnResponseChanging(string value);
    partial void OnResponseChanged();
    #endregion
		
		public ExperianBWVerifyResponse()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExperianBWVerifyResponseId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ExperianBWVerifyResponseId
		{
			get
			{
				return this._ExperianBWVerifyResponseId;
			}
			set
			{
				if ((this._ExperianBWVerifyResponseId != value))
				{
					this.OnExperianBWVerifyResponseIdChanging(value);
					this.SendPropertyChanging();
					this._ExperianBWVerifyResponseId = value;
					this.SendPropertyChanged("ExperianBWVerifyResponseId");
					this.OnExperianBWVerifyResponseIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaitTimeInSeconds", DbType="Int NOT NULL")]
		public int WaitTimeInSeconds
		{
			get
			{
				return this._WaitTimeInSeconds;
			}
			set
			{
				if ((this._WaitTimeInSeconds != value))
				{
					this.OnWaitTimeInSecondsChanging(value);
					this.SendPropertyChanging();
					this._WaitTimeInSeconds = value;
					this.SendPropertyChanged("WaitTimeInSeconds");
					this.OnWaitTimeInSecondsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNumber", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string AccountNumber
		{
			get
			{
				return this._AccountNumber;
			}
			set
			{
				if ((this._AccountNumber != value))
				{
					this.OnAccountNumberChanging(value);
					this.SendPropertyChanging();
					this._AccountNumber = value;
					this.SendPropertyChanged("AccountNumber");
					this.OnAccountNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Response", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Response
		{
			get
			{
				return this._Response;
			}
			set
			{
				if ((this._Response != value))
				{
					this.OnResponseChanging(value);
					this.SendPropertyChanging();
					this._Response = value;
					this.SendPropertyChanged("Response");
					this.OnResponseChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExperianResponse")]
	public partial class ExperianResponse : DbEntity<ExperianResponse>, INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ExperianResponseId;
		
		private int _WaitTimeInSeconds;
		
		private string _Forename;
		
		private string _Surname;
		
		private string _Response;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExperianResponseIdChanging(int value);
    partial void OnExperianResponseIdChanged();
    partial void OnWaitTimeInSecondsChanging(int value);
    partial void OnWaitTimeInSecondsChanged();
    partial void OnForenameChanging(string value);
    partial void OnForenameChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnResponseChanging(string value);
    partial void OnResponseChanged();
    #endregion
		
		public ExperianResponse()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExperianResponseId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ExperianResponseId
		{
			get
			{
				return this._ExperianResponseId;
			}
			set
			{
				if ((this._ExperianResponseId != value))
				{
					this.OnExperianResponseIdChanging(value);
					this.SendPropertyChanging();
					this._ExperianResponseId = value;
					this.SendPropertyChanged("ExperianResponseId");
					this.OnExperianResponseIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaitTimeInSeconds", DbType="Int NOT NULL")]
		public int WaitTimeInSeconds
		{
			get
			{
				return this._WaitTimeInSeconds;
			}
			set
			{
				if ((this._WaitTimeInSeconds != value))
				{
					this.OnWaitTimeInSecondsChanging(value);
					this.SendPropertyChanging();
					this._WaitTimeInSeconds = value;
					this.SendPropertyChanged("WaitTimeInSeconds");
					this.OnWaitTimeInSecondsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Forename", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Forename
		{
			get
			{
				return this._Forename;
			}
			set
			{
				if ((this._Forename != value))
				{
					this.OnForenameChanging(value);
					this.SendPropertyChanging();
					this._Forename = value;
					this.SendPropertyChanged("Forename");
					this.OnForenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Response", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Response
		{
			get
			{
				return this._Response;
			}
			set
			{
				if ((this._Response != value))
				{
					this.OnResponseChanging(value);
					this.SendPropertyChanging();
					this._Response = value;
					this.SendPropertyChanged("Response");
					this.OnResponseChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GraydonCompanyReport")]
	public partial class GraydonCompanyReport : DbEntity<GraydonCompanyReport>, INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GraydonCompanyReportId;
		
		private int _WaitTimeInSeconds;
		
		private int _OrderReference;
		
		private string _CompanyMatchIdentifier;
		
		private string _CompanyProductIdentifier;
		
		private string _CompanyReport;
		
		private string _CompanyProducts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGraydonCompanyReportIdChanging(int value);
    partial void OnGraydonCompanyReportIdChanged();
    partial void OnWaitTimeInSecondsChanging(int value);
    partial void OnWaitTimeInSecondsChanged();
    partial void OnOrderReferenceChanging(int value);
    partial void OnOrderReferenceChanged();
    partial void OnCompanyMatchIdentifierChanging(string value);
    partial void OnCompanyMatchIdentifierChanged();
    partial void OnCompanyProductIdentifierChanging(string value);
    partial void OnCompanyProductIdentifierChanged();
    partial void OnCompanyReportChanging(string value);
    partial void OnCompanyReportChanged();
    partial void OnCompanyProductsChanging(string value);
    partial void OnCompanyProductsChanged();
    #endregion
		
		public GraydonCompanyReport()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GraydonCompanyReportId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GraydonCompanyReportId
		{
			get
			{
				return this._GraydonCompanyReportId;
			}
			set
			{
				if ((this._GraydonCompanyReportId != value))
				{
					this.OnGraydonCompanyReportIdChanging(value);
					this.SendPropertyChanging();
					this._GraydonCompanyReportId = value;
					this.SendPropertyChanged("GraydonCompanyReportId");
					this.OnGraydonCompanyReportIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaitTimeInSeconds", DbType="Int NOT NULL")]
		public int WaitTimeInSeconds
		{
			get
			{
				return this._WaitTimeInSeconds;
			}
			set
			{
				if ((this._WaitTimeInSeconds != value))
				{
					this.OnWaitTimeInSecondsChanging(value);
					this.SendPropertyChanging();
					this._WaitTimeInSeconds = value;
					this.SendPropertyChanged("WaitTimeInSeconds");
					this.OnWaitTimeInSecondsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderReference", DbType="Int NOT NULL")]
		public int OrderReference
		{
			get
			{
				return this._OrderReference;
			}
			set
			{
				if ((this._OrderReference != value))
				{
					this.OnOrderReferenceChanging(value);
					this.SendPropertyChanging();
					this._OrderReference = value;
					this.SendPropertyChanged("OrderReference");
					this.OnOrderReferenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyMatchIdentifier", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CompanyMatchIdentifier
		{
			get
			{
				return this._CompanyMatchIdentifier;
			}
			set
			{
				if ((this._CompanyMatchIdentifier != value))
				{
					this.OnCompanyMatchIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CompanyMatchIdentifier = value;
					this.SendPropertyChanged("CompanyMatchIdentifier");
					this.OnCompanyMatchIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyProductIdentifier", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CompanyProductIdentifier
		{
			get
			{
				return this._CompanyProductIdentifier;
			}
			set
			{
				if ((this._CompanyProductIdentifier != value))
				{
					this.OnCompanyProductIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CompanyProductIdentifier = value;
					this.SendPropertyChanged("CompanyProductIdentifier");
					this.OnCompanyProductIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyReport", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CompanyReport
		{
			get
			{
				return this._CompanyReport;
			}
			set
			{
				if ((this._CompanyReport != value))
				{
					this.OnCompanyReportChanging(value);
					this.SendPropertyChanging();
					this._CompanyReport = value;
					this.SendPropertyChanged("CompanyReport");
					this.OnCompanyReportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyProducts", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CompanyProducts
		{
			get
			{
				return this._CompanyProducts;
			}
			set
			{
				if ((this._CompanyProducts != value))
				{
					this.OnCompanyProductsChanging(value);
					this.SendPropertyChanging();
					this._CompanyProducts = value;
					this.SendPropertyChanged("CompanyProducts");
					this.OnCompanyProductsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IncomingBankGatewayScotiaFile")]
	public partial class IncomingBankGatewayScotiaFile : DbEntity<IncomingBankGatewayScotiaFile>, INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _FileName;
		
		private System.Data.Linq.Binary _FileData;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnFileChanging(System.Data.Linq.Binary value);
    partial void OnFileChanged();
    #endregion
		
		public IncomingBankGatewayScotiaFile()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileData", DbType="VarBinary(max)", CanBeNull=true)]
		public System.Data.Linq.Binary FileData
		{
			get
			{
                return this._FileData;
			}
			set
			{
                if ((this._FileData != value))
				{
					this.OnFileChanging(value);
					this.SendPropertyChanging();
                    this._FileData = value;
					this.SendPropertyChanged("FileData");
					this.OnFileChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IovationDataOutput")]
	public partial class IovationDataOutput : DbEntity<IovationDataOutput>, INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IovationDataOutputId;
		
		private int _WaitTimeInSeconds;
		
		private string _Type;
		
		private string _Response;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIovationDataOutputIdChanging(int value);
    partial void OnIovationDataOutputIdChanged();
    partial void OnWaitTimeInSecondsChanging(int value);
    partial void OnWaitTimeInSecondsChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnResponseChanging(string value);
    partial void OnResponseChanged();
    #endregion
		
		public IovationDataOutput()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IovationDataOutputId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IovationDataOutputId
		{
			get
			{
				return this._IovationDataOutputId;
			}
			set
			{
				if ((this._IovationDataOutputId != value))
				{
					this.OnIovationDataOutputIdChanging(value);
					this.SendPropertyChanging();
					this._IovationDataOutputId = value;
					this.SendPropertyChanged("IovationDataOutputId");
					this.OnIovationDataOutputIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaitTimeInSeconds", DbType="Int NOT NULL")]
		public int WaitTimeInSeconds
		{
			get
			{
				return this._WaitTimeInSeconds;
			}
			set
			{
				if ((this._WaitTimeInSeconds != value))
				{
					this.OnWaitTimeInSecondsChanging(value);
					this.SendPropertyChanging();
					this._WaitTimeInSeconds = value;
					this.SendPropertyChanged("WaitTimeInSeconds");
					this.OnWaitTimeInSecondsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Response", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Response
		{
			get
			{
				return this._Response;
			}
			set
			{
				if ((this._Response != value))
				{
					this.OnResponseChanging(value);
					this.SendPropertyChanging();
					this._Response = value;
					this.SendPropertyChanged("Response");
					this.OnResponseChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MSSQLDeploy")]
	public partial class MSSQLDeploy : DbEntity<MSSQLDeploy>, INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.DateTime _Date;
		
		private string _Name;
		
		private string _MD5;
		
		private System.Nullable<int> _Revision;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnMD5Changing(string value);
    partial void OnMD5Changed();
    partial void OnRevisionChanging(System.Nullable<int> value);
    partial void OnRevisionChanged();
    #endregion
		
		public MSSQLDeploy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MD5", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string MD5
		{
			get
			{
				return this._MD5;
			}
			set
			{
				if ((this._MD5 != value))
				{
					this.OnMD5Changing(value);
					this.SendPropertyChanging();
					this._MD5 = value;
					this.SendPropertyChanged("MD5");
					this.OnMD5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Revision", DbType="Int")]
		public System.Nullable<int> Revision
		{
			get
			{
				return this._Revision;
			}
			set
			{
				if ((this._Revision != value))
				{
					this.OnRevisionChanging(value);
					this.SendPropertyChanging();
					this._Revision = value;
					this.SendPropertyChanged("Revision");
					this.OnRevisionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
